import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { ScreenWorkspace } from './ScreenWorkspace';
import { parseScreenDocument, readScreenPixel, screenBytes, screenGeometry } from '../assets/screenDocument';
import { resolveProjectPalette } from '../assets/paletteDocument';

afterEach(() => { cleanup(); localStorage.clear(); });

function renderWorkspace() {
  const props = { projectPalette: resolveProjectPalette([], 4), onAddSource: vi.fn(), onAddLiveScreen: vi.fn(), onNotice: vi.fn() };
  render(<ScreenWorkspace {...props} />);
  return props;
}
const canvas = () => screen.getByRole('application', { name: /Screen/ });

/* Persisting a whole frame buffer is debounced in the editor, so the stored
 * document is awaited rather than read straight after an edit. */
const stored = () => waitFor(() => {
  const raw = localStorage.getItem('8bit-net-dev:screen');
  expect(raw).not.toBeNull();
  return parseScreenDocument(raw!);
});
const pixelAt = async (x: number, y: number) => {
  const document = await stored();
  return readScreenPixel(screenBytes(document), screenGeometry(document.mode), x, y);
};

describe('ScreenWorkspace', () => {
  it('starts from a blank MODE 5 screen of the right size', async () => {
    renderWorkspace();
    expect((await stored()).mode).toBe('bbc-mode-5');
    expect(screenBytes(await stored())).toHaveLength(10240);
    expect(canvas()).toHaveAccessibleName('Screen untitled-screen, 160 by 256 pixels');
  });

  it('paints at the keyboard cursor and reports the colour under it', async () => {
    renderWorkspace();
    fireEvent.keyDown(canvas(), { key: 'ArrowRight' });
    fireEvent.keyDown(canvas(), { key: 'ArrowDown' });
    fireEvent.keyDown(canvas(), { key: 'Enter' });
    expect(await pixelAt(1, 1)).toBe(1);
    expect(screen.getByRole('status')).toHaveTextContent('Pixel 2, 2 of 160 by 256 is logical colour 1');
  });

  it('moves eight pixels at a time with Shift and stops at the edges', () => {
    renderWorkspace();
    fireEvent.keyDown(canvas(), { key: 'ArrowRight', shiftKey: true });
    expect(screen.getByRole('status')).toHaveTextContent('Pixel 9, 1');
    for (let step = 0; step < 3; step += 1) fireEvent.keyDown(canvas(), { key: 'ArrowUp' });
    expect(screen.getByRole('status')).toHaveTextContent('Pixel 9, 1');
  });

  it('selects a logical colour within the mode and fills with it', async () => {
    const { onNotice } = renderWorkspace();
    fireEvent.click(screen.getByRole('radio', { name: 'Logical colour 3' }));
    fireEvent.click(screen.getByRole('button', { name: 'Fill screen' }));
    expect(await pixelAt(0, 0)).toBe(3);
    expect(await pixelAt(159, 255)).toBe(3);
    expect(onNotice).toHaveBeenCalledWith('Screen filled with logical colour 3');
  });

  it('offers exactly the logical colours the chosen mode has', async () => {
    renderWorkspace();
    expect(screen.getAllByRole('radio')).toHaveLength(4);
    fireEvent.change(screen.getByLabelText('Display mode'), { target: { value: 'bbc-mode-2' } });
    expect(screen.getAllByRole('radio')).toHaveLength(16);
    expect(screenBytes(await stored())).toHaveLength(20480);
  });

  it('says how lossy a mode conversion was rather than implying it was clean', () => {
    const { onNotice } = renderWorkspace();
    fireEvent.change(screen.getByLabelText('Display mode'), { target: { value: 'bbc-mode-1' } });
    expect(onNotice).toHaveBeenCalledWith(expect.stringMatching(/Converted to MODE 1: [\d,]+ pixels resampled and 0 clamped/));
  });

  it('reports the colours the picture uses and the frame-buffer size', () => {
    renderWorkspace();
    fireEvent.click(screen.getByRole('radio', { name: 'Logical colour 2' }));
    fireEvent.keyDown(canvas(), { key: 'Enter' });
    expect(screen.getByText('10,240 bytes')).toBeInTheDocument();
    expect(screen.getByText('0, 2')).toBeInTheDocument();
  });

  it('offers generated source and a live build target', () => {
    const { onAddSource, onAddLiveScreen } = renderWorkspace();
    fireEvent.change(screen.getByLabelText('Screen name'), { target: { value: 'title screen' } });
    fireEvent.click(screen.getByRole('button', { name: 'Add generated source' }));
    expect(onAddSource).toHaveBeenCalledWith('title-screen.asm', expect.stringContaining('.screen_title_screen'));
    fireEvent.click(screen.getByRole('button', { name: 'Add live screen build target' }));
    expect(onAddLiveScreen).toHaveBeenCalledWith('title-screen', expect.stringContaining('"schema": "8bit-net.screen"'));
  });

  it('says the generated bytes are the picture only', () => {
    renderWorkspace();
    expect(screen.getByText(/do not include the mode change or the palette/)).toBeInTheDocument();
  });
});
