import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { useState } from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { ProjectFile, SourceBookmark } from '../project/project';
import type { LanguageTargetContext } from '../language/languageTarget';
import { SourceWorkspace } from './SourceWorkspace';

afterEach(() => {
  cleanup(); localStorage.clear(); vi.restoreAllMocks();
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined });
});

function Harness({ initial = '' }: { initial?: string }) {
  const [files, setFiles] = useState<ProjectFile[]>([{
    id: 'main', name: 'main.bas', content: initial, language: 'bbc-basic', modified: false,
  }]);
  return <SourceWorkspace
    files={files}
    activeFileId="main"
    onSelectFile={() => undefined}
    onChange={(id, content) => setFiles((current) => current.map((file) => file.id === id ? { ...file, content } : file))}
    onNewFile={() => undefined}
    onRenameFile={() => undefined}
    onDeleteFile={() => undefined}
    onDownloadFile={() => undefined}
    onSave={() => undefined}
    onCaretChange={() => undefined}
    onNotice={() => undefined}
  />;
}

describe('functional source workspace', () => {
  it('compares the saved baseline with the working copy and navigates changed working lines', async () => {
    const file: ProjectFile = { id: 'main', name: 'main.asm', saved: true, savedContent: '.start\n LDA #1\n RTS', content: '.start\n LDA #2\n STA &70\n RTS', language: '6502', modified: true };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.click(screen.getByRole('button', { name: 'Compare saved' }));
    const comparison = screen.getByRole('dialog', { name: 'Saved comparison for main.asm' });
    expect(comparison).toHaveTextContent('2 added');
    expect(comparison).toHaveTextContent('1 removed');
    const changedRow = within(comparison).getByRole('row', { name: /3 \+ STA &70/ });
    fireEvent.click(changedRow);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    await waitFor(() => expect(editor.selectionStart).toBe(editor.value.indexOf(' STA &70')));
  }, 10_000);

  it('exposes generated provenance and blocks editor mutation while retaining inspection', () => {
    const change = vi.fn(); const notice = vi.fn();
    const file: ProjectFile = { id: 'generated', name: 'sprites.inc', saved: true, savedContent: 'EQUB 1,2,3', content: 'EQUB 1,2,3', language: '6502', modified: false, kind: 'generated', access: 'read-only', generator: 'Sprite asset hero.asset.json' };
    render(<SourceWorkspace files={[file]} activeFileId="generated" onSelectFile={() => undefined} onChange={change} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={notice} />);
    expect(screen.getByLabelText('Edit sprites.inc')).toHaveAttribute('readonly');
    expect(screen.getByRole('status')).toHaveTextContent('Generated by Sprite asset hero.asset.json');
    expect(screen.getByLabelText('read only')).toHaveTextContent('RO');
    fireEvent.change(screen.getByLabelText('Edit sprites.inc'), { target: { value: 'MUTATED' } });
    expect(change).not.toHaveBeenCalled();
    expect(notice).toHaveBeenCalledWith('sprites.inc is read-only; source was not changed');
    fireEvent.click(screen.getByText('Edit', { selector: 'summary' }));
    fireEvent.click(screen.getByRole('button', { name: 'Cut' }));
    expect(notice).toHaveBeenCalledWith('sprites.inc is read-only; use Copy instead of Cut');
  });

  it('edits the controlled source document and automatically numbers BASIC lines', () => {
    render(<Harness initial="10 PRINT &quot;HELLO&quot;" />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { key: 'Enter' });
    expect(editor.value).toBe('10 PRINT "HELLO"\n20 ');
  });

  it('does not auto-number a selected range or split non-whitespace text after the caret', () => {
    render(<Harness initial={'10 PRINT "HELLO"'} />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(3, 3);
    expect(fireEvent.keyDown(editor, { key: 'Enter' })).toBe(true);
    expect(editor.value).toBe('10 PRINT "HELLO"');
    editor.setSelectionRange(3, 8);
    expect(fireEvent.keyDown(editor, { key: 'Enter' })).toBe(true);
    expect(editor.value).toBe('10 PRINT "HELLO"');
    editor.setSelectionRange(editor.value.length, editor.value.length);
    expect(fireEvent.keyDown(editor, { key: 'Enter' })).toBe(false);
    expect(editor.value).toBe('10 PRINT "HELLO"\n20 ');
  });

  it('does not show completion until invoked and inserts the chosen command', async () => {
    render(<Harness initial="10 PRI" />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    expect(screen.queryByRole('listbox', { name: 'Command completion' })).not.toBeInTheDocument();
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    expect(await screen.findByRole('listbox', { name: 'Command completion' })).toBeVisible();
    fireEvent.click(screen.getByRole('option', { name: /PRINT/ }));
    expect(editor.value).toBe('10 PRINT');
  });

  it('inserts a functional BASIC statement snippet through completion', async () => {
    render(<Harness initial="10 FOR_" />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    const option = await screen.findByRole('option', { name: /FOR_LOOP/ });
    expect(option).toHaveTextContent('snippet');
    fireEvent.click(option);
    expect(editor.value).toBe('10 FOR I%=0 TO 10:PRINT I%:NEXT');
  });

  it('automatically opens, incrementally filters and accepts ranked completion without offering it inside strings', async () => {
    render(<Harness initial="10 " />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    fireEvent.change(editor, { target: { value: '10 PR', selectionStart: 5, selectionEnd: 5 } });
    const list = await screen.findByRole('listbox', { name: 'Command completion' });
    expect(list).toBeVisible();
    expect(screen.getByRole('option', { name: /PRINT/ })).toHaveTextContent('REFERENCE');
    fireEvent.change(editor, { target: { value: '10 PRI', selectionStart: 6, selectionEnd: 6 } });
    await waitFor(() => {
      expect(screen.getByRole('listbox', { name: 'Command completion' })).toBeVisible();
      expect(screen.getByRole('option', { name: /PRINT/ })).toBeVisible();
      expect(screen.queryByRole('option', { name: /PROC/ })).not.toBeInTheDocument();
    });
    fireEvent.keyDown(editor, { key: 'Enter' });
    expect(editor.value).toBe('10 PRINT');

    fireEvent.change(editor, { target: { value: '10 PRINT "PR', selectionStart: 12, selectionEnd: 12 } });
    await waitFor(() => expect(screen.queryByRole('listbox', { name: 'Command completion' })).not.toBeInTheDocument());
  });

  it('performs real replace-all operations', () => {
    render(<Harness initial={'10 PRINT "ONE"\n20 PRINT "ONE"'} />);
    fireEvent.click(screen.getByRole('button', { name: /Find/ }));
    fireEvent.change(screen.getByPlaceholderText('Find'), { target: { value: 'ONE' } });
    fireEvent.change(screen.getByPlaceholderText('Replace'), { target: { value: 'TWO' } });
    fireEvent.click(screen.getByRole('button', { name: 'All' }));
    expect(screen.getByLabelText('Edit main.bas')).toHaveValue('10 PRINT "TWO"\n20 PRINT "TWO"');
  });

  it('navigates BASIC lines and exact reference ranges while exposing unresolved diagnostics', async () => {
    render(<Harness initial={'10 GOTO 30\n20 GOSUB 99\n30 END'} />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    fireEvent.change(screen.getByLabelText('BASIC line number'), { target: { value: '30' } });
    fireEvent.click(screen.getByRole('button', { name: 'Go' }));
    await waitFor(() => expect(editor.selectionStart).toBe(editor.value.indexOf('30 END')));

    fireEvent.click(screen.getByRole('button', { name: 'Previous BASIC reference' }));
    await waitFor(() => expect(editor.value.slice(editor.selectionStart, editor.selectionEnd)).toBe('99'));
    expect(screen.getByLabelText('BASIC line diagnostics')).toHaveTextContent('GOSUB 99');

    fireEvent.click(screen.getByRole('button', { name: /Go to target 30;/ }));
    await waitFor(() => expect(editor.value.slice(editor.selectionStart, editor.selectionEnd)).toBe('30'));
  });

  it('filters the parsed project symbol index and navigates the first match by keyboard', () => {
    const navigate = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n.start\n JSR paint_frame', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.paint_frame\n RTS', language: '6502', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.change(screen.getByLabelText('Find project symbol'), { target: { value: 'paint lib' } });
    expect(screen.getByRole('list', { name: 'Project symbols' })).toHaveTextContent('paint_frame');
    expect(screen.queryByText('start', { selector: 'strong' })).not.toBeInTheDocument();
    fireEvent.keyDown(screen.getByLabelText('Find project symbol'), { key: 'Enter' });
    expect(navigate).toHaveBeenCalledWith('lib', 1, 2, 11);
  });

  it('invokes save from the standard keyboard shortcut', () => {
    const save = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.bas', content: '', language: 'bbc-basic', modified: false };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={save} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.keyDown(screen.getByLabelText('Edit main.bas'), { key: 's', ctrlKey: true });
    expect(save).toHaveBeenCalledOnce();
  });

  it('provides keyboard paths for save all, close and reopen-closed', () => {
    const save = vi.fn(); const saveAll = vi.fn(); const close = vi.fn(); const reopen = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.bas', content: '', language: 'bbc-basic', modified: true };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={save} onSaveAll={saveAll} onCloseFile={close} onReopenClosed={reopen} canReopenClosed onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.bas');
    fireEvent.keyDown(editor, { key: 's', ctrlKey: true, shiftKey: true });
    fireEvent.keyDown(editor, { key: 'w', ctrlKey: true });
    fireEvent.keyDown(editor, { key: 't', ctrlKey: true, shiftKey: true });
    expect(saveAll).toHaveBeenCalledOnce(); expect(save).not.toHaveBeenCalled();
    expect(close).toHaveBeenCalledWith('main'); expect(reopen).toHaveBeenCalledOnce();
    expect(screen.getByRole('button', { name: 'Close main.bas' })).toHaveAttribute('title', expect.stringContaining('unsaved content remains'));
  });

  it('routes split, tab conversion, formatting and confirmed revert commands', async () => {
    const revert = vi.fn(() => true);
    const file: ProjectFile = { id: 'main', name: 'main.bas', content: '10\tPRINT "DIRTY"  ', savedContent: '10 END', language: 'bbc-basic', modified: true };
    function CommandHarness() {
      const [current, setCurrent] = useState(file);
      return <SourceWorkspace files={[current]} activeFileId="main" onSelectFile={() => undefined} onChange={(_, content) => setCurrent((value) => ({ ...value, content }))} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onRevert={revert} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<CommandHarness />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    fireEvent.keyDown(editor, { key: 'f', altKey: true, shiftKey: true });
    await waitFor(() => expect(editor.value).toBe('10  PRINT "DIRTY"'));
    editor.setSelectionRange(2, 2);
    fireEvent.keyDown(editor, { key: 'Enter', ctrlKey: true, shiftKey: true });
    await waitFor(() => expect(editor.value).toBe('10\n  PRINT "DIRTY"'));
    fireEvent.keyDown(editor, { key: 'r', ctrlKey: true, altKey: true });
    expect(revert).toHaveBeenCalledWith('main');
  });

  it('provides token definitions and resolved source navigation', () => {
    const file: ProjectFile = { id: 'main', name: 'main.6502', content: ' BNE loop\n.loop\n RTS', language: '6502', modified: false };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    expect(screen.getByTitle(/BNE label.*Branch when zero is clear/)).toBeVisible();
    const jump = screen.getByTitle('Declared in main.6502');
    expect(jump).toBeEnabled();
    fireEvent.click(jump);
  });

  it('shows dismissible, cited and processor-aware rich opcode help on keyboard focus', () => {
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' LDA &4000,X', language: '6502', modified: false };
    render(<SourceWorkspace files={[file]} activeFileId="main" processor="6502" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.focus(screen.getByTitle(/LDA .*Load A/));
    const help = screen.getByLabelText('LDA token help');
    expect(help).toHaveTextContent('6502-family instruction');
    expect(help).toHaveTextContent(/SUPPORTED.*NMOS 6502/);
    expect(help).toHaveTextContent(/FLAGS.*N.*Z/);
    const cycles = screen.getByRole('table', { name: 'LDA instruction cycles' });
    expect(cycles).toHaveTextContent(/Absolute, X.*4 to 5.*crosses a page/i);
    expect(screen.getByRole('link', { name: /W65C02S Datasheet/ })).toHaveAttribute('href', 'https://www.westerndesigncenter.com/documentation/w65c02s.pdf');
    fireEvent.click(screen.getByRole('button', { name: 'STA' }));
    expect(screen.getByLabelText('STA token help')).toHaveTextContent(/Store the accumulator to memory/);
    fireEvent.click(screen.getByRole('button', { name: 'Dismiss STA help' }));
    expect(screen.queryByLabelText('LDA token help')).not.toBeInTheDocument();
  });

  it('shows the same structured token help on pointer hover and keyboard focus', () => {
    const file: ProjectFile = { id: 'main', name: 'main.bas', content: '10 MODE 2', language: 'bbc-basic', modified: false };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const token = screen.getByRole('button', { name: 'MODE' });
    fireEvent.mouseEnter(token);
    const pointerHelp = screen.getByLabelText('MODE token help');
    expect(pointerHelp).toHaveTextContent(/MODE mode.*Select a display mode/s);
    expect(pointerHelp).toHaveTextContent(/mode.*Display mode number/s);
    expect(pointerHelp).toHaveTextContent(/EXAMPLES.*MODE 7/s);
    expect(pointerHelp).toHaveTextContent(/EFFECTS.*Clears the screen/s);
    fireEvent.mouseLeave(token);
    expect(screen.queryByLabelText('MODE token help')).not.toBeInTheDocument();
    fireEvent.focus(token);
    expect(screen.getByLabelText('MODE token help')).toHaveTextContent(/SUPPORTED.*BBC BASIC/);
    expect(screen.getByRole('link', { name: /BBC Microcomputer System User Guide/ })).toBeVisible();
  });

  it('invalidates displayed instruction help when the selected processor changes', async () => {
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' STZ &70', language: '6502', modified: false };
    function ProcessorHarness() {
      const [processor, setProcessor] = useState<'6502' | '65c02'>('6502');
      return <><button type="button" onClick={() => setProcessor('65c02')}>Select 65C12</button><SourceWorkspace files={[file]} activeFileId="main" processor={processor} onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} /></>;
    }
    render(<ProcessorHarness />);
    fireEvent.focus(screen.getByRole('button', { name: 'STZ' }));
    expect(screen.getByLabelText('STZ token help')).toHaveTextContent('INCOMPATIBLE');
    fireEvent.click(screen.getByRole('button', { name: 'Select 65C12' }));
    await waitFor(() => expect(screen.getByLabelText('STZ token help')).toHaveTextContent('SUPPORTED'));
    expect(screen.getByLabelText('STZ token help')).not.toHaveTextContent('not available on the selected NMOS 6502 target');
  });

  it('updates structured BASIC help when the selected machine changes', async () => {
    const file: ProjectFile = { id: 'main', name: 'sound.bas', content: '10 SOUND 1,-15,53,20', language: 'bbc-basic', modified: false };
    const bbc: LanguageTargetContext = { processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC Micro Model B', romId: 'os12-basic2', romLabel: 'OS 1.20 / BASIC II', romReady: true, enabledCapabilities: [] };
    function TargetHarness() {
      const [languageTarget, setLanguageTarget] = useState(bbc);
      return <><button type="button" onClick={() => setLanguageTarget({ ...bbc, machineId: 'atom', machineLabel: 'Acorn Atom', romId: 'atom', romLabel: 'Atom ROMs' })}>Select Atom</button><SourceWorkspace files={[file]} languageTarget={languageTarget} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} /></>;
    }
    render(<TargetHarness />);
    fireEvent.focus(screen.getByRole('button', { name: 'SOUND' }));
    const help = screen.getByLabelText('SOUND token help');
    expect(help).toHaveTextContent(/SUPPORTED.*BBC BASIC II.*BBC Micro Model B/);
    expect(help).toHaveTextContent(/channel.*Simple form 0–3/);
    fireEvent.click(screen.getByRole('button', { name: 'Select Atom' }));
    await waitFor(() => expect(screen.getByLabelText('SOUND token help')).toHaveTextContent('INCOMPATIBLE'));
    expect(screen.getByLabelText('SOUND token help')).toHaveTextContent(/not compatible with the selected Acorn Atom profile/);
  });

  it('explains an explicitly requested incompatible candidate without inserting it', async () => {
    const file: ProjectFile = { id: 'main', name: 'atom.bas', content: '10 SOU', language: 'bbc-basic', modified: false };
    const atom: LanguageTargetContext = { processor: '6502', machineId: 'atom', machineLabel: 'Acorn Atom', romId: 'atom-mos', romLabel: 'Atom MOS', romReady: true, enabledCapabilities: [], toolchainId: '8bit-net.basic.atom' };
    const change = vi.fn(); const notice = vi.fn();
    render(<SourceWorkspace files={[file]} languageTarget={atom} activeFileId="main" onSelectFile={() => undefined} onChange={change} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={notice} />);
    const editor = screen.getByLabelText('Edit atom.bas') as HTMLTextAreaElement; editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    const option = await screen.findByRole('option', { name: /SOUND/ });
    expect(option).toHaveAttribute('aria-disabled', 'true');
    expect(option).toHaveTextContent(/UNAVAILABLE.*not compatible with the selected Acorn Atom profile/i);
    fireEvent.click(option);
    expect(change).not.toHaveBeenCalled();
    expect(notice).toHaveBeenLastCalledWith(expect.stringMatching(/not compatible with the selected Acorn Atom profile/i));
  });

  it('provides parameter-aware signature help and caret definition navigation', async () => {
    const basic: ProjectFile = { id: 'basic', name: 'sound.bas', content: '10 SOUND 1,-15,120,', language: 'bbc-basic', modified: false };
    const { unmount } = render(<SourceWorkspace files={[basic]} activeFileId="basic" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const basicEditor = screen.getByLabelText('Edit sound.bas') as HTMLTextAreaElement;
    basicEditor.setSelectionRange(basicEditor.value.length, basicEditor.value.length);
    fireEvent.click(basicEditor);
    await waitFor(() => expect(screen.getByLabelText('Active parameter 4 of 4')).toHaveTextContent('duration'));
    unmount();

    const assembly: ProjectFile = { id: 'asm', name: 'jump.asm', content: ' JMP draw\n.draw\n RTS', language: '6502', modified: false };
    render(<SourceWorkspace files={[assembly]} activeFileId="asm" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const assemblyEditor = screen.getByLabelText('Edit jump.asm') as HTMLTextAreaElement;
    assemblyEditor.setSelectionRange(assembly.content.indexOf('draw'), assembly.content.indexOf('draw'));
    fireEvent.keyDown(assemblyEditor, { key: 'F12' });
    await waitFor(() => expect(assemblyEditor.selectionStart).toBe(assembly.content.indexOf('.draw') + 1));
    expect(assemblyEditor.selectionEnd).toBe(assembly.content.indexOf('.draw') + 5);
  });

  it('shows alternative signature forms without moving editor focus', async () => {
    const basic: ProjectFile = { id: 'basic', name: 'call.bas', content: '10 CALL &1900,A%,', language: 'bbc-basic', modified: false };
    render(<SourceWorkspace files={[basic]} activeFileId="basic" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit call.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    editor.focus();
    fireEvent.click(editor);
    await waitFor(() => expect(screen.getByLabelText('CALL alternative forms')).toBeVisible());
    expect(screen.getByText('SIGNATURE 2/2')).toBeVisible();
    expect(screen.getByLabelText('Active parameter 2 of 2')).toHaveTextContent('variable…');
    expect(screen.getByLabelText('Active parameter 2 of 2')).toHaveTextContent('optional or repeated');
    expect(document.activeElement).toBe(editor);
    fireEvent.click(screen.getByRole('button', { name: 'Previous signature form' }));
    expect(screen.getByText('SIGNATURE 1/2')).toBeVisible();
    expect(screen.getByLabelText('Active parameter 1 of 1')).toHaveTextContent('address');
    editor.focus();
    fireEvent.keyDown(editor, { key: 'Escape' });
    expect(screen.queryByLabelText('CALL alternative forms')).not.toBeInTheDocument();
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true, shiftKey: true });
    await waitFor(() => expect(screen.getByLabelText('CALL alternative forms')).toBeVisible());
    expect(document.activeElement).toBe(editor);
  });

  it('creates, renames, searches, disables and navigates project bookmarks', async () => {
    const navigate = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: '.start\n LDA #1\n RTS', language: '6502', modified: false },
      { id: 'other', name: 'other.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    function BookmarkHarness() {
      const [bookmarks, setBookmarks] = useState<SourceBookmark[]>([{ id: 'other-mark', fileId: 'other', line: 1, column: 1, name: 'Draw routine', description: '', scope: 'project', enabled: true, anchor: '.draw' }]);
      return <SourceWorkspace files={[files[0]!]} projectFiles={files} bookmarks={bookmarks} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} onNavigateSource={navigate} onAddBookmark={(fileId, line, column, name) => setBookmarks((current) => [...current, { id: 'added', fileId, line, column, name, description: '', scope: 'project', enabled: true, anchor: 'LDA #1' }])} onUpdateBookmark={(id, changes) => setBookmarks((current) => current.map((bookmark) => bookmark.id === id ? { ...bookmark, ...changes } : bookmark))} onRemoveBookmark={(id) => setBookmarks((current) => current.filter((bookmark) => bookmark.id !== id))} />;
    }
    const prompt = vi.spyOn(window, 'prompt').mockReturnValueOnce('Load value').mockReturnValueOnce('Load accumulator').mockReturnValueOnce('Check accumulator ownership before sharing');
    render(<BookmarkHarness />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const position = files[0]!.content.indexOf('LDA'); editor.setSelectionRange(position, position); fireEvent.click(editor);
    fireEvent.click(screen.getByRole('button', { name: 'Add bookmark' }));
    expect(await screen.findByRole('button', { name: /source bookmark Load value/ })).toBeVisible();
    fireEvent.click(screen.getByText('All project bookmarks'));
    fireEvent.change(screen.getByLabelText('Search project bookmarks'), { target: { value: 'Load' } });
    expect(screen.getByLabelText('Project source bookmarks')).toHaveTextContent('Load value');
    expect(screen.getByLabelText('Project source bookmarks')).not.toHaveTextContent('Draw routine');
    fireEvent.click(screen.getByRole('button', { name: 'Rename bookmark Load value' }));
    expect(screen.getByLabelText('Project source bookmarks')).toHaveTextContent('Load accumulator');
    fireEvent.click(screen.getByRole('button', { name: 'Change bookmark Load accumulator to private scope' }));
    expect(screen.getByLabelText('Project source bookmarks')).toHaveTextContent('PRIVATE');
    fireEvent.click(screen.getByRole('button', { name: 'Edit description for bookmark Load accumulator' }));
    expect(screen.getByLabelText('Project source bookmarks')).toHaveTextContent('Check accumulator ownership before sharing');
    fireEvent.click(screen.getByRole('button', { name: 'Disable bookmark Load accumulator' }));
    expect(screen.getByRole('button', { name: 'Enable bookmark Load accumulator' })).toBeVisible();
    fireEvent.change(screen.getByLabelText('Search project bookmarks'), { target: { value: '' } });
    fireEvent.click(screen.getByRole('button', { name: 'Bookmark ↓' }));
    expect(navigate).toHaveBeenCalledWith('other', 1, 1);
    expect(prompt).toHaveBeenCalledTimes(3);
  }, 15_000);

  it('opens and closes independently labelled source split panes by control or shortcut', () => {
    const source: ProjectFile = { id: 'main', name: 'main.asm', content: '.start\n RTS', language: '6502', modified: false };
    const split = vi.fn(); const close = vi.fn();
    const common = { files: [source], activeFileId: 'main', onSelectFile: () => undefined, onChange: () => undefined, onNewFile: () => undefined, onRenameFile: () => undefined, onDeleteFile: () => undefined, onDownloadFile: () => undefined, onSave: () => undefined, onCaretChange: () => undefined, onNotice: () => undefined };
    const { unmount } = render(<SourceWorkspace {...common} paneId="primary" splitOpen={false} onRequestSplit={split} onCloseSplit={close} />);
    fireEvent.click(screen.getByRole('button', { name: 'Split editor' }));
    expect(split).toHaveBeenLastCalledWith('main');
    fireEvent.keyDown(screen.getByLabelText('Edit main.asm'), { key: '\\', ctrlKey: true });
    expect(split).toHaveBeenCalledTimes(2);
    unmount();
    render(<SourceWorkspace {...common} paneId="secondary" splitOpen onRequestSplit={split} onCloseSplit={close} />);
    expect(screen.getByLabelText('Secondary source editor pane')).toBeVisible();
    fireEvent.keyDown(screen.getByLabelText('Edit main.asm'), { key: '\\', ctrlKey: true });
    expect(close).toHaveBeenCalledTimes(1);
  });

  it('offers optional authoritative BBC BASIC type hints and an honest untyped assembly state', () => {
    const basic: ProjectFile = { id: 'basic', name: 'types.bas', content: '10 score%=1:name$="Ada":ratio=2.5', language: 'bbc-basic', modified: false };
    const { unmount } = render(<SourceWorkspace files={[basic]} activeFileId="basic" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Type hints' }));
    expect(screen.getByText('TYPE HINTS')).toBeVisible();
    expect(screen.getByRole('button', { name: /score%.*signed integer.*32-bit/i })).toBeVisible();
    unmount();
    const assembly: ProjectFile = { id: 'asm', name: 'untyped.asm', content: '.start\n RTS', language: '6502', modified: false };
    render(<SourceWorkspace files={[assembly]} activeFileId="asm" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Type hints' }));
    expect(screen.getByText('Untyped source: no types are inferred.')).toBeVisible();
  });

  it('shows navigable authoritative cc65 C type and signature details', () => {
    const file: ProjectFile = { id: 'c', name: 'types.c', content: 'unsigned long ticks;\nvoid __fastcall__ draw(unsigned char frame) {\n  int local = 1;\n}', language: 'c', modified: false };
    const target: LanguageTargetContext = { processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC Micro Model B', romId: 'os12-basic2', romLabel: 'OS 1.20 / BASIC II', romReady: true, enabledCapabilities: [], toolchainId: 'cc65.c-bbc' };
    render(<SourceWorkspace files={[file]} languageTarget={target} activeFileId="c" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Type hints' }));
    screen.getByRole('region', { name: 'Authoritative source type hints' });
    expect(screen.getByRole('button', { name: /ticks.*variable.*32-bit.*Signedness: unsigned/i })).toBeVisible();
    expect(screen.getByRole('button', { name: /draw.*return.*code symbol.*Returns: void.*Parameters: unsigned char frame.*Calling convention: __fastcall__/i })).toBeVisible();
    expect(screen.getByRole('button', { name: /frame.*parameter.*unsigned char.*8-bit.*Signedness: unsigned/i })).toBeVisible();
    expect(screen.getByRole('button', { name: /local.*variable.*int.*16-bit.*Signedness: signed/i })).toBeVisible();
  });

  it('completes and navigates symbols through the real project INCLUDE graph', async () => {
    const navigate = vi.fn();
    const initial: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n JSR dr', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    function ProjectHarness() {
      const [projectFiles, setProjectFiles] = useState(initial);
      const main = projectFiles[0]!;
      return <SourceWorkspace files={[main]} projectFiles={projectFiles} activeFileId="main" processor="6502" onSelectFile={() => undefined} onChange={(id, content) => setProjectFiles((current) => current.map((file) => file.id === id ? { ...file, content } : file))} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<ProjectHarness />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const emptyOperand = 'INCLUDE "lib.asm"\n JSR ';
    fireEvent.change(editor, { target: { value: emptyOperand, selectionStart: emptyOperand.length, selectionEnd: emptyOperand.length } });
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    expect(await screen.findByRole('option', { name: /draw.*lib\.asm:1.*project-/i })).toBeVisible();
    expect(screen.getByRole('option', { name: /OSWRCH/ })).toBeVisible();
    expect(screen.queryByRole('option', { name: /opcode.*LDA/i })).not.toBeInTheDocument();
    fireEvent.change(editor, { target: { value: 'INCLUDE "lib.asm"\n JSR dra', selectionStart: 30 } });
    const option = await screen.findByRole('option', { name: /draw.*lib\.asm:1.*project-/i });
    fireEvent.click(option);
    await waitFor(() => expect(editor.value).toBe('INCLUDE "lib.asm"\n JSR draw'));
    const symbolPosition = editor.value.lastIndexOf('draw') + 2;
    editor.setSelectionRange(symbolPosition, symbolPosition);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(navigate).toHaveBeenCalledWith('lib', 1, 2, 4));
    expect(screen.getByTitle('Declared in included source lib.asm')).toHaveTextContent('lib.asm:1');
  }, 10_000);

  it('opens an exact assembly operand with an ordinary pointer click', async () => {
    const navigate = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n JSR draw', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const target = editor.value.lastIndexOf('draw') + 2;
    editor.setSelectionRange(target, target);
    fireEvent.click(editor);
    await waitFor(() => expect(navigate).toHaveBeenCalledWith('lib', 1, 2, 4));
  });

  it('requires a choice when a directly clicked target is ambiguous', async () => {
    const navigate = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "one.asm"\nINCLUDE "two.asm"\n JSR draw', language: '6502', modified: false },
      { id: 'one', name: 'one.asm', content: '.draw\n RTS', language: '6502', modified: false },
      { id: 'two', name: 'two.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const target = editor.value.lastIndexOf('draw') + 2;
    editor.setSelectionRange(target, target);
    fireEvent.click(editor);
    const chooser = await screen.findByRole('dialog', { name: /Definitions for draw/i });
    expect(chooser).toHaveTextContent('2 definitions');
    expect(chooser).toHaveTextContent('one.asm');
    expect(chooser).toHaveTextContent('two.asm');
    expect(navigate).not.toHaveBeenCalled();
  });

  it('routes a maintained MOS token to Research instead of inventing a source declaration', async () => {
    const research = vi.fn(); const notice = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' JSR OSWRCH', language: '6502', modified: false };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onResearch={research} onCaretChange={() => undefined} onNotice={notice} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const target = editor.value.indexOf('OSWRCH') + 2;
    editor.setSelectionRange(target, target);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(research).toHaveBeenCalledWith('6502', 'OSWRCH'));
    expect(notice).toHaveBeenCalledWith(expect.stringContaining('no editable project declaration'));
  });

  it('opens the exact current build symbol table for a generated symbol without claiming editable source', async () => {
    const openGenerated = vi.fn(); const notice = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' LDA generated_buffer', language: '6502', modified: false };
    const target: LanguageTargetContext = {
      processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC Micro Model B', romId: 'os12-basic2', romLabel: 'OS 1.20 / BASIC II', romReady: true,
      enabledCapabilities: [], toolchainId: 'stardot.beebasm', generatedSymbols: [{ name: 'generated_buffer', value: 0x3200 }],
    };
    render(<SourceWorkspace files={[file]} languageTarget={target} languageBuildRevision="current:build-42" activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onOpenGeneratedSymbol={openGenerated} onCaretChange={() => undefined} onNotice={notice} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const targetPosition = editor.value.indexOf('generated_buffer') + 2;
    editor.setSelectionRange(targetPosition, targetPosition);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(openGenerated).toHaveBeenCalledWith('generated_buffer'));
    expect(notice).toHaveBeenCalledWith(expect.stringMatching(/exact current build.*read-only artifact symbol evidence/i));
  });

  it('opens real cc65 SDK documents from system includes and known declarations', async () => {
    const openSdk = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.c', content: '#include <acorn.h>\nint main(void) { acorn_oswrch(65); return 0; }', language: 'c', modified: false };
    const target: LanguageTargetContext = {
      processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC Micro Model B', romId: 'os12-basic2', romLabel: 'OS 1.20 / BASIC II', romReady: true,
      enabledCapabilities: [], toolchainId: 'cc65.c-bbc',
    };
    render(<SourceWorkspace files={[file]} languageTarget={target} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onOpenSdkDocument={openSdk} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.c') as HTMLTextAreaElement;

    const includePosition = editor.value.indexOf('acorn.h') + 2;
    editor.setSelectionRange(includePosition, includePosition);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(openSdk).toHaveBeenCalledWith('acorn.h'));

    openSdk.mockClear();
    const declarationPosition = editor.value.indexOf('acorn_oswrch') + 2;
    editor.setSelectionRange(declarationPosition, declarationPosition);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(openSdk).toHaveBeenCalledWith('acorn.h', 'ACORN_OSWRCH'));
  });

  it('does not expose cc65 SDK navigation under an unrelated toolchain', async () => {
    const openSdk = vi.fn(); const notice = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.c', content: '#include <acorn.h>\nvoid main(void) { acorn_oswrch(65); }', language: 'c', modified: false };
    const target: LanguageTargetContext = { processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC B', romId: 'os12', romLabel: 'OS 1.20', romReady: true, enabledCapabilities: [], toolchainId: '8bit-net.asm.6502' };
    render(<SourceWorkspace files={[file]} languageTarget={target} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onOpenSdkDocument={openSdk} onCaretChange={() => undefined} onNotice={notice} />);
    const editor = screen.getByLabelText('Edit main.c') as HTMLTextAreaElement;
    const position = editor.value.indexOf('acorn_oswrch') + 2;
    editor.setSelectionRange(position, position);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(notice).toHaveBeenCalledWith(expect.stringContaining('not declared')));
    expect(openSdk).not.toHaveBeenCalled();
  });

  it('does not retain generated-symbol navigation after current build provenance is removed', async () => {
    const openGenerated = vi.fn(); const notice = vi.fn();
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' LDA generated_buffer', language: '6502', modified: false };
    const baseTarget: LanguageTargetContext = { processor: '6502', machineId: 'bbc-b', machineLabel: 'BBC Micro Model B', romId: 'os12-basic2', romLabel: 'OS 1.20 / BASIC II', romReady: true, enabledCapabilities: [], toolchainId: 'stardot.beebasm' };
    const common = { files: [file], activeFileId: 'main', onSelectFile: () => undefined, onChange: () => undefined, onNewFile: () => undefined, onRenameFile: () => undefined, onDeleteFile: () => undefined, onDownloadFile: () => undefined, onSave: () => undefined, onOpenGeneratedSymbol: openGenerated, onCaretChange: () => undefined, onNotice: notice };
    const view = render(<SourceWorkspace {...common} languageTarget={{ ...baseTarget, generatedSymbols: [{ name: 'generated_buffer', value: 0x3200 }] }} languageBuildRevision="current:build-42" />);
    view.rerender(<SourceWorkspace {...common} languageTarget={baseTarget} languageBuildRevision="stale:no-current-artifact" />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const targetPosition = editor.value.indexOf('generated_buffer') + 2;
    editor.setSelectionRange(targetPosition, targetPosition);
    fireEvent.keyDown(editor, { key: 'F12' });
    await waitFor(() => expect(notice).toHaveBeenCalledWith(expect.stringContaining('not declared')));
    expect(openGenerated).not.toHaveBeenCalled();
  });

  it('offers only declared BASIC line targets in a numeric GOTO operand', async () => {
    render(<Harness initial={'10 GOTO \n100 PRINT "READY"\n200 END'} />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    const content = '10 GOTO 10\n100 PRINT "READY"\n200 END';
    fireEvent.change(editor, { target: { value: content, selectionStart: 10, selectionEnd: 10 } });
    expect(await screen.findByRole('option', { name: /line.*100/i })).toBeVisible();
    expect(screen.queryByRole('option', { name: /command.*PRINT/i })).not.toBeInTheDocument();
  });

  it('peeks connected references and exposes source-location history controls', async () => {
    const navigate = vi.fn(); const back = vi.fn(); const forward = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n JSR draw\n BNE draw', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n RTS', language: '6502', modified: false },
      { id: 'other', name: 'other.asm', content: ' JSR draw', language: '6502', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} canNavigateBack canNavigateForward onNavigateBack={back} onNavigateForward={forward} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.indexOf('draw'), editor.value.indexOf('draw'));
    fireEvent.keyDown(editor, { key: 'F12', shiftKey: true });
    const peek = await screen.findByRole('dialog', { name: 'References for DRAW' });
    expect(peek).toHaveTextContent('3 locations');
    expect(peek).toHaveTextContent('lib.asm:1:2');
    expect(peek).not.toHaveTextContent('other.asm');
    fireEvent.click(screen.getByRole('button', { name: /lib\.asm:1:2.*declaration/i }));
    expect(navigate).toHaveBeenCalledWith('lib', 1, 2, 4);
    fireEvent.click(screen.getByRole('button', { name: /← Back/ }));
    fireEvent.keyDown(editor, { key: 'ArrowRight', altKey: true });
    expect(back).toHaveBeenCalledOnce(); expect(forward).toHaveBeenCalledOnce();
  });

  it('shows navigable incoming and outgoing direct-call hierarchy without treating branches as calls', async () => {
    const navigate = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n.main\n JSR draw\n BNE draw\n RTS', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n JSR plot\n RTS\n.plot\n RTS', language: '6502', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const position = editor.value.indexOf('draw') + 2;
    editor.setSelectionRange(position, position);
    fireEvent.keyDown(editor, { key: 'H', altKey: true, shiftKey: true });
    const hierarchy = await screen.findByRole('dialog', { name: /Call hierarchy for draw/i });
    expect(hierarchy).toHaveTextContent(/Incoming callers\s+1/);
    expect(hierarchy).toHaveTextContent(/Outgoing callees\s+1/);
    expect(hierarchy).toHaveTextContent('maincallsdraw');
    expect(hierarchy).toHaveTextContent('drawcallsplot');
    expect(hierarchy).toHaveTextContent('Direct calls only');
    expect(within(hierarchy).getAllByRole('button', { name: 'Open call site' })).toHaveLength(2);
    fireEvent.click(within(hierarchy).getAllByRole('button', { name: 'Open callee' })[1]!);
    expect(navigate).toHaveBeenCalledWith('lib', 4, 2, 4);
  });

  it('navigates separate C declarations, implementations and type definitions', async () => {
    const navigate = vi.fn(); const notice = vi.fn();
    const files: ProjectFile[] = [
      { id: 'main', name: 'main.c', content: '#include "api.h"\nbyte value;\nvoid frame(void) {\n draw();\n}', language: 'c', modified: false },
      { id: 'api', name: 'api.h', content: '#include "draw.c"\ntypedef unsigned char byte;\nvoid draw(void);', language: 'c', modified: false },
      { id: 'impl', name: 'draw.c', content: 'void draw(void) {\n value = 1;\n}', language: 'c', modified: false },
    ];
    render(<SourceWorkspace files={[files[0]!]} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={notice} />);
    const editor = screen.getByLabelText('Edit main.c') as HTMLTextAreaElement;
    const call = editor.value.lastIndexOf('draw') + 1;
    editor.setSelectionRange(call, call);
    fireEvent.click(screen.getByRole('button', { name: 'Declaration' }));
    await waitFor(() => expect(navigate).toHaveBeenLastCalledWith('api', 3, 6, 4));
    fireEvent.click(screen.getByRole('button', { name: 'Implementation' }));
    await waitFor(() => expect(navigate).toHaveBeenLastCalledWith('impl', 1, 6, 4));
    editor.setSelectionRange(editor.value.indexOf('byte') + 1, editor.value.indexOf('byte') + 1);
    fireEvent.click(screen.getByRole('button', { name: 'Type definition' }));
    await waitFor(() => expect(navigate).toHaveBeenLastCalledWith('api', 2, 23, 4));
    expect(notice).toHaveBeenLastCalledWith(expect.stringMatching(/Type definition.*api\.h:2/i));
  });

  it('previews, applies and undoes a collision-safe project assembly rename', async () => {
    const initial: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n JSR draw\n BNE draw', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    function RenameHarness() {
      const [files, setFiles] = useState(initial);
      const [active, setActive] = useState('main');
      const updateMany = (changes: Array<{ id: string; content: string }>) => setFiles((current) => current.map((file) => ({ ...file, content: changes.find((change) => change.id === file.id)?.content ?? file.content })));
      return <SourceWorkspace files={files} projectFiles={files} activeFileId={active} onSelectFile={setActive} onChange={(id, content) => updateMany([{ id, content }])} onChangeFiles={updateMany} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<RenameHarness />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const position = editor.value.indexOf('draw'); editor.setSelectionRange(position, position);
    fireEvent.keyDown(editor, { key: 'F12', shiftKey: true });
    await screen.findByRole('dialog', { name: 'References for DRAW' });
    await screen.findByDisplayValue('DRAW');
    fireEvent.change(screen.getByLabelText('Replacement symbol name'), { target: { value: 'paint_frame' } });
    await waitFor(() => expect(screen.getByLabelText('Replacement symbol name')).toHaveValue('paint_frame'));
    fireEvent.click(screen.getByRole('button', { name: 'Preview rename' }));
    const preview = await screen.findByRole('list', { name: 'Project rename file changes' });
    expect(preview).toHaveTextContent('main.asm2 replacements');
    expect(preview).toHaveTextContent('lib.asm1 replacement');
    fireEvent.click(screen.getByRole('button', { name: 'Apply project rename' }));
    await waitFor(() => expect(screen.getByLabelText('Edit main.asm')).toHaveValue('INCLUDE "lib.asm"\n JSR paint_frame\n BNE paint_frame'));
    fireEvent.click(screen.getByRole('tab', { name: 'lib.asm' }));
    expect(screen.getByLabelText('Edit lib.asm')).toHaveValue('.paint_frame\n RTS');
    fireEvent.click(screen.getByRole('button', { name: 'Undo last rename' }));
    await waitFor(() => expect(screen.getByLabelText('Edit lib.asm')).toHaveValue('.draw\n RTS'));
    fireEvent.click(screen.getByRole('tab', { name: 'main.asm' }));
    expect(screen.getByLabelText('Edit main.asm')).toHaveValue(initial[0]!.content);
  }, 10_000);

  it('previews and atomically applies a uniquely resolved BASIC routine rename', async () => {
    function BasicRenameHarness() {
      const [file, setFile] = useState<ProjectFile>({ id: 'basic', name: 'routines.bas', content: '10 DEF PROCdraw\n20 PROCdraw', language: 'bbc-basic', modified: false });
      return <SourceWorkspace files={[file]} projectFiles={[file]} activeFileId="basic" onSelectFile={() => undefined} onChange={(_, content) => setFile((current) => ({ ...current, content }))} onChangeFiles={(changes) => setFile((current) => ({ ...current, content: changes.find((change) => change.id === current.id)?.content ?? current.content }))} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<BasicRenameHarness />);
    const editor = screen.getByLabelText('Edit routines.bas') as HTMLTextAreaElement;
    const position = editor.value.lastIndexOf('PROCdraw'); editor.setSelectionRange(position, position);
    fireEvent.keyDown(editor, { key: 'F12', shiftKey: true });
    await screen.findByRole('dialog', { name: /References for PROCDRAW/i });
    await screen.findByDisplayValue('PROCDRAW');
    expect(screen.getByText('Rename uniquely resolved symbol')).toBeVisible();
    fireEvent.change(screen.getByLabelText('Replacement symbol name'), { target: { value: 'PROCpaint' } });
    await waitFor(() => expect(screen.getByLabelText('Replacement symbol name')).toHaveValue('PROCpaint'));
    fireEvent.click(screen.getByRole('button', { name: 'Preview rename' }));
    expect(await screen.findByRole('list', { name: 'Project rename file changes' })).toHaveTextContent('2 replacements');
    fireEvent.click(screen.getByRole('button', { name: 'Apply project rename' }));
    await waitFor(() => expect(editor).toHaveValue('10 DEF PROCpaint\n20 PROCpaint'));
  });

  it('expires displayed completion when the bound build revision changes', async () => {
    const file: ProjectFile = { id: 'main', name: 'main.asm', content: ' LD', language: '6502', modified: false };
    const common = { files: [file], projectFiles: [file], activeFileId: 'main', onSelectFile: () => undefined, onChange: () => undefined, onNewFile: () => undefined, onRenameFile: () => undefined, onDeleteFile: () => undefined, onDownloadFile: () => undefined, onSave: () => undefined, onCaretChange: () => undefined, onNotice: () => undefined };
    const view = render(<SourceWorkspace {...common} languageBuildRevision="current:build-one" />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    expect(await screen.findByRole('listbox', { name: 'Command completion' })).toBeVisible();
    view.rerender(<SourceWorkspace {...common} languageBuildRevision="current:build-two" />);
    await waitFor(() => expect(screen.queryByRole('listbox', { name: 'Command completion' })).not.toBeInTheDocument());
  });

  it('expires a rename preview when any indexed project source changes', async () => {
    const initial: ProjectFile[] = [
      { id: 'main', name: 'main.asm', content: 'INCLUDE "lib.asm"\n JSR draw', language: '6502', modified: false },
      { id: 'lib', name: 'lib.asm', content: '.draw\n RTS', language: '6502', modified: false },
    ];
    const common = { files: initial, activeFileId: 'main', onSelectFile: () => undefined, onChange: () => undefined, onChangeFiles: () => undefined, onNewFile: () => undefined, onRenameFile: () => undefined, onDeleteFile: () => undefined, onDownloadFile: () => undefined, onSave: () => undefined, onCaretChange: () => undefined, onNotice: () => undefined };
    const view = render(<SourceWorkspace {...common} projectFiles={initial} />);
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    const position = editor.value.indexOf('draw'); editor.setSelectionRange(position, position);
    fireEvent.keyDown(editor, { key: 'F12', shiftKey: true });
    await screen.findByRole('dialog', { name: 'References for DRAW' });
    await screen.findByDisplayValue('DRAW');
    fireEvent.change(screen.getByLabelText('Replacement symbol name'), { target: { value: 'paint' } });
    await waitFor(() => expect(screen.getByLabelText('Replacement symbol name')).toHaveValue('paint'));
    fireEvent.click(screen.getByRole('button', { name: 'Preview rename' }));
    await screen.findByRole('list', { name: 'Project rename file changes' });
    expect(screen.getByRole('button', { name: 'Apply project rename' })).toBeEnabled();
    const changed = [initial[0]!, { ...initial[1]!, content: '.draw\n NOP\n RTS' }];
    view.rerender(<SourceWorkspace {...common} files={changed} projectFiles={changed} />);
    await waitFor(() => expect(screen.queryByRole('button', { name: 'Apply project rename' })).not.toBeInTheDocument());
  });

  it('converts Acorn numbers, endian bytes and target address validity', () => {
    render(<Harness initial="10 PRINT &41" />);
    fireEvent.click(screen.getByText('Number and address converter'));
    fireEvent.change(screen.getByLabelText('Number converter value'), { target: { value: '&4142' } });
    expect(screen.getByText('42 41')).toBeVisible();
    expect(screen.getByText('41 42')).toBeVisible();
    expect(screen.getByText('Valid 16-bit 6502-family address.')).toBeVisible();
    cleanup();

    const arm: ProjectFile = { id: 'arm', name: 'main.arm', content: 'start:\n B start', language: 'arm', modified: false };
    render(<SourceWorkspace files={[arm]} activeFileId="arm" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    fireEvent.click(screen.getByText('Number and address converter'));
    expect(screen.getByLabelText('Number converter width')).toHaveValue('32');
    fireEvent.change(screen.getByLabelText('Number converter value'), { target: { value: '&8002' } });
    expect(screen.getByText('ARM instruction addresses must be word aligned.')).toBeVisible();
  });

  it('persists bounded editor typography, tab width and wrapping preferences', () => {
    render(<Harness initial={'10 PRINT "A LONG SOURCE LINE"'} />);
    fireEvent.click(screen.getByText('Preferences'));
    fireEvent.change(screen.getByLabelText('Editor font size'), { target: { value: '15' } });
    fireEvent.change(screen.getByLabelText('Editor line height'), { target: { value: '28' } });
    fireEvent.change(screen.getByLabelText('Editor tab size'), { target: { value: '4' } });
    fireEvent.click(screen.getByLabelText('Editor word wrap'));
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    const layout = editor.closest('.source-editor-layout') as HTMLElement;
    expect(layout.style.getPropertyValue('--editor-font-size')).toBe('15px');
    expect(layout.style.getPropertyValue('--editor-line-height')).toBe('28px');
    expect(layout.style.getPropertyValue('--editor-tab-size')).toBe('4');
    expect(editor.style.whiteSpace).toBe('pre-wrap');
    cleanup();

    render(<Harness />);
    fireEvent.click(screen.getByText('Preferences'));
    expect(screen.getByLabelText('Editor font size')).toHaveValue(15);
    expect(screen.getByLabelText('Editor line height')).toHaveValue(28);
    expect(screen.getByLabelText('Editor tab size')).toHaveValue('4');
    expect(screen.getByLabelText('Editor word wrap')).toBeChecked();
    fireEvent.click(screen.getByRole('button', { name: 'Reset view' }));
    expect(screen.getByLabelText('Editor font size')).toHaveValue(11);
  });

  it('exposes per-file encoding and line-ending controls without changing editor text', () => {
    const changed = vi.fn();
    function FormatHarness() {
      const [source, setSource] = useState<ProjectFile>({ id: 'main', name: 'main.bas', content: '10 PRINT "£"\n20 END', language: 'bbc-basic', encoding: 'utf-8', lineEnding: 'lf', modified: false });
      return <SourceWorkspace files={[source]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onChangeTextFormat={(id, encoding, lineEnding) => { changed(id, encoding, lineEnding); setSource((current) => ({ ...current, encoding, lineEnding })); }} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<FormatHarness />);
    fireEvent.click(screen.getByText('Preferences'));
    fireEvent.change(screen.getByLabelText('Source encoding for main.bas'), { target: { value: 'windows-1252' } });
    fireEvent.change(screen.getByLabelText('Line endings for main.bas'), { target: { value: 'crlf' } });
    expect(changed).toHaveBeenNthCalledWith(1, 'main', 'windows-1252', 'lf');
    expect(changed).toHaveBeenNthCalledWith(2, 'main', 'windows-1252', 'crlf');
    expect(screen.getByLabelText('Edit main.bas')).toHaveValue('10 PRINT "£"\n20 END');
  });

  it('announces bounded large-source mode and pauses eager outline scanning', () => {
    const source: ProjectFile = { id: 'large', name: 'large.asm', content: `.start\n${'; padding\n'.repeat(30_000)}`, language: '6502', modified: false };
    render(<SourceWorkspace files={[source]} activeFileId="large" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    expect(screen.getByRole('status')).toHaveTextContent('Large source mode');
    expect(screen.getByText('No numbered lines or labels yet.')).toBeVisible();
    expect(screen.getByLabelText('Edit large.asm')).toHaveValue(source.content);
  });

  it('clears language-provider state when switching documents', async () => {
    const files: ProjectFile[] = [
      { id: 'asm', name: 'main.asm', content: ' LDA #1', language: '6502', modified: false },
      { id: 'basic', name: 'main.bas', content: '10 PRINT "OK"', language: 'bbc-basic', modified: false },
    ];
    function SwitchHarness() {
      const [active, setActive] = useState('asm');
      return <SourceWorkspace files={files} projectFiles={files} activeFileId={active} onSelectFile={setActive} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />;
    }
    render(<SwitchHarness />);
    fireEvent.mouseEnter(screen.getByTitle(/LDA .*Load A/));
    expect(screen.getByLabelText('LDA token help')).toHaveTextContent('Load A');
    fireEvent.click(screen.getByRole('tab', { name: 'main.bas' }));
    await waitFor(() => expect(screen.queryByLabelText('LDA token help')).not.toBeInTheDocument());
    expect(screen.getByLabelText('Edit main.bas')).toBeVisible();
  });

  it('uses a safe numbering gap and applies or undoes a previewed BASIC renumber', async () => {
    const source = '10 PRINT "GOTO 90":GOTO 20\n20 DATA 20,GOTO 10:REM GOTO 20\n30 GOTO 999';
    render(<Harness initial={source} />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;

    editor.setSelectionRange(source.indexOf('\n'), source.indexOf('\n'));
    fireEvent.change(screen.getByLabelText('BASIC numbering increment'), { target: { value: '15' } });
    fireEvent.keyDown(editor, { key: 'Enter' });
    await waitFor(() => expect(editor.value).toContain('\n15 \n20 DATA'));

    fireEvent.change(screen.getByLabelText('BASIC numbering start'), { target: { value: '100' } });
    fireEvent.change(screen.getByLabelText('BASIC numbering increment'), { target: { value: '10' } });
    fireEvent.click(screen.getByRole('button', { name: 'Preview renumber' }));
    const preview = screen.getByLabelText('BASIC renumber preview');
    expect(preview).toHaveTextContent('4 lines');
    expect(preview).toHaveTextContent('1 unresolved target');
    expect(screen.getByLabelText('Unresolved BASIC line references')).toHaveTextContent('GOTO 999');
    fireEvent.click(screen.getByRole('button', { name: 'Apply renumber' }));
    await waitFor(() => expect(editor.value).toContain('100 PRINT "GOTO 90":GOTO 120'));
    expect(editor.value).toContain('120 DATA 20,GOTO 10:REM GOTO 20');
    expect(editor.value).toContain('130 GOTO 999');
    fireEvent.click(screen.getByRole('button', { name: 'Undo renumber' }));
    await waitFor(() => expect(editor.value).toContain('10 PRINT "GOTO 90":GOTO 20'));
    expect(editor.value).toContain('\n15 \n20 DATA');
  });

  it('previews and atomically applies a physical-line BASIC renumber range', async () => {
    const source = '10 GOTO 30\n20 GOSUB 40\n30 GOTO 20\n40 END\n50 GOTO 30';
    render(<Harness initial={source} />);
    fireEvent.change(screen.getByLabelText('BASIC renumber scope'), { target: { value: 'range' } });
    fireEvent.change(screen.getByLabelText('BASIC renumber first physical line'), { target: { value: '2' } });
    fireEvent.change(screen.getByLabelText('BASIC renumber last physical line'), { target: { value: '4' } });
    fireEvent.change(screen.getByLabelText('BASIC numbering start'), { target: { value: '25' } });
    fireEvent.change(screen.getByLabelText('BASIC numbering increment'), { target: { value: '5' } });
    fireEvent.click(screen.getByRole('button', { name: 'Preview renumber' }));
    const preview = screen.getByLabelText('BASIC renumber preview');
    expect(preview).toHaveTextContent('3 lines');
    expect(preview).toHaveTextContent('2 references');
    expect(preview).toHaveTextContent('20');
    expect(preview).toHaveTextContent('25');
    fireEvent.click(screen.getByRole('button', { name: 'Apply renumber' }));
    await waitFor(() => expect(screen.getByLabelText('Edit main.bas')).toHaveValue('10 GOTO 30\n25 GOSUB 35\n30 GOTO 25\n35 END\n50 GOTO 30'));
  });

  it('navigates enclosing loops, diagnostics and saved changes with capability-aware controls', async () => {
    const file: ProjectFile = { id: 'main', name: 'navigation.bas', saved: true, savedContent: '10 FOR I=1 TO 2\n20 PRINT I\n30 NEXT\n40 END', content: '10 FOR I=1 TO 2\n20 GOTO 99\n30 NEXT\n30 END', language: 'bbc-basic', modified: true };
    render(<SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const editor = screen.getByLabelText('Edit navigation.bas') as HTMLTextAreaElement;
    const gotoPosition = editor.value.indexOf('GOTO');
    editor.setSelectionRange(gotoPosition, gotoPosition);
    fireEvent.keyUp(editor, { key: 'o' });
    await waitFor(() => expect(screen.getByLabelText('Current source scope')).toHaveTextContent('FOR/NEXT · lines 1 to 3'));
    fireEvent.click(within(screen.getByLabelText('Current source scope')).getByRole('button', { name: 'End' }));
    await waitFor(() => expect(editor.selectionStart).toBe(editor.value.indexOf('NEXT')));

    editor.setSelectionRange(0, 0);
    fireEvent.keyDown(editor, { key: 'F8' });
    await waitFor(() => expect(editor.value.slice(editor.selectionStart, editor.selectionEnd)).toBe('9'));
    editor.setSelectionRange(0, 0);
    fireEvent.keyDown(editor, { key: 'F8', altKey: true });
    await waitFor(() => expect(editor.selectionStart).toBe(editor.value.indexOf('20 GOTO')));

    fireEvent.click(screen.getByText('Navigate', { selector: 'summary' }));
    expect(screen.getByRole('button', { name: /Previous diagnostic/ })).toBeEnabled();
    expect(screen.getByRole('button', { name: /Previous saved change/ })).toBeEnabled();
  });

  it('previews, applies and undoes the safe missing BASIC line-number quick fix', async () => {
    render(<Harness initial={'10 PRINT "A"\nGOTO 99\n20 END'} />);
    fireEvent.click(screen.getByRole('button', { name: 'Preview quick fix' }));
    const preview = screen.getByRole('dialog', { name: 'BASIC quick fix preview' });
    expect(preview).toHaveTextContent('Insert line 15');
    expect(preview).toHaveTextContent('15 GOTO 99');
    expect(screen.getAllByRole('button', { name: 'Manual fix required' }).every((button) => button.hasAttribute('disabled'))).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'Apply quick fix' }));
    await waitFor(() => expect(screen.getByLabelText('Edit main.bas')).toHaveValue('10 PRINT "A"\n15 GOTO 99\n20 END'));
    fireEvent.click(screen.getByRole('button', { name: 'Undo last quick fix' }));
    await waitFor(() => expect(screen.getByLabelText('Edit main.bas')).toHaveValue('10 PRINT "A"\nGOTO 99\n20 END'));
  });

  it('pastes exact plain text from the browser clipboard without interpreting markup', async () => {
    const pasted = '<b>PRINT "£ π 😀"</b>\r\n';
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { readText: vi.fn(async () => pasted) } });
    render(<Harness initial="10 REM " />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    const editSummary = screen.getByText('Edit', { selector: 'summary' });
    const editMenu = editSummary.closest('details') as HTMLDetailsElement;
    fireEvent.click(editSummary);
    expect(editMenu.open).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'Paste plain text' }));
    expect(editMenu.open).toBe(false);
    await waitFor(() => expect(editor.value).toBe(`10 REM ${pasted.replace('\r\n', '\n')}`));
    expect(screen.queryByRole('dialog', { name: 'Paste plain text' })).not.toBeInTheDocument();
  });

  it('cancels delayed cut and paste results when their captured source becomes stale', async () => {
    let finishRead!: (text: string) => void; let finishWrite!: () => void;
    const readText = vi.fn(() => new Promise<string>((resolve) => { finishRead = resolve; }));
    const writeText = vi.fn(() => new Promise<void>((resolve) => { finishWrite = resolve; }));
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { readText, writeText } });
    const notice = vi.fn();
    function ClipboardHarness() {
      const [file, setFile] = useState<ProjectFile>({ id: 'main', name: 'main.bas', content: '10 PRINT "OLD"', language: 'bbc-basic', modified: false });
      return <SourceWorkspace files={[file]} activeFileId="main" onSelectFile={() => undefined} onChange={(_, content) => setFile((current) => ({ ...current, content }))} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={notice} />;
    }
    render(<ClipboardHarness />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    fireEvent.click(screen.getByText('Edit', { selector: 'summary' }));
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.click(screen.getByRole('button', { name: 'Paste plain text' }));
    fireEvent.change(editor, { target: { value: '10 PRINT "NEW"' } });
    await act(async () => finishRead('\n20 END'));
    expect(editor.value).toBe('10 PRINT "NEW"');
    expect(notice).toHaveBeenCalledWith(expect.stringContaining('Paste cancelled because the source changed'));

    editor.setSelectionRange(0, 2);
    fireEvent.click(screen.getByRole('button', { name: 'Cut' }));
    fireEvent.change(editor, { target: { value: '30 END' } });
    await act(async () => finishWrite());
    expect(editor.value).toBe('30 END');
    expect(notice).toHaveBeenCalledWith(expect.stringContaining('Cut cancelled because the source changed'));
  });

  it('explains denied clipboard reads and inserts only explicit fallback text', async () => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { readText: vi.fn(async () => { throw new DOMException('denied', 'NotAllowedError'); }) } });
    render(<Harness initial="10 END" />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.click(screen.getByText('Edit', { selector: 'summary' }));
    fireEvent.click(screen.getByRole('button', { name: 'Paste plain text' }));
    const fallback = await screen.findByRole('dialog', { name: 'Paste plain text' });
    expect(fallback).toHaveTextContent('browser denied clipboard permission');
    expect(fallback).toHaveTextContent('Markup is never interpreted or executed');
    fireEvent.change(screen.getByLabelText('Plain-text paste fallback'), { target: { value: '\n20 PRINT "<b>TEXT</b>"' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert text' }));
    await waitFor(() => expect(editor.value).toContain('20 PRINT "<b>TEXT</b>"'));
  });

  it('runs line commands with predictable undo/redo and offers a paste-permission fallback', async () => {
    render(<Harness initial={'10 PRINT "ONE"\n20 END'} />);
    const editor = screen.getByLabelText('Edit main.bas') as HTMLTextAreaElement;
    editor.setSelectionRange(0, '10 PRINT "ONE"'.length);
    fireEvent.keyDown(editor, { key: '/', ctrlKey: true });
    await waitFor(() => expect(editor.value.startsWith('10 REM PRINT "ONE"')).toBe(true));
    fireEvent.keyDown(editor, { key: 'z', ctrlKey: true });
    await waitFor(() => expect(editor.value.startsWith('10 PRINT "ONE"')).toBe(true));
    fireEvent.keyDown(editor, { key: 'z', ctrlKey: true, shiftKey: true });
    await waitFor(() => expect(editor.value.startsWith('10 REM PRINT "ONE"')).toBe(true));

    fireEvent.click(screen.getByText('Edit', { selector: 'summary' }));
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.click(screen.getByRole('button', { name: 'Paste plain text' }));
    const fallback = await screen.findByRole('dialog', { name: 'Paste plain text' });
    fireEvent.change(screen.getByLabelText('Plain-text paste fallback'), { target: { value: '\n30 PRINT "PASTED"' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert text' }));
    await waitFor(() => expect(editor.value.endsWith('30 PRINT "PASTED"')).toBe(true));
    expect(fallback).not.toBeInTheDocument();
  });
});

describe('the outline and issues that the language adapter provides', () => {
  const workspace = (file: ProjectFile) => render(<SourceWorkspace files={[file]} activeFileId={file.id} onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);

  it('nests what a 6502 label owns under it, and shows a constant’s value beside it', () => {
    workspace({
      id: 'main', name: 'main.asm', language: '6502', modified: false,
      content: 'INCLUDE "lib.asm"\n.start\nscreen = &7C00\n  RTS\n',
    } as ProjectFile);
    const panel = within(screen.getByRole('complementary', { name: 'Source outline' }));
    const constant = panel.getByRole('button', { name: /screen/ });
    expect(constant.className).toContain('outline-depth-1');
    expect(constant).toHaveTextContent('&7C00');
    /* An include is a statement about the file, not about a label. */
    expect(panel.getByRole('button', { name: /lib\.asm/ }).className).not.toContain('outline-depth');
  });

  it('reports a duplicate label in this file, and navigates to it', () => {
    const navigate = vi.fn();
    render(<SourceWorkspace files={[{ id: 'main', name: 'main.asm', language: '6502', modified: false, content: '.start\n  RTS\n.start\n  RTS' } as ProjectFile]} activeFileId="main" onSelectFile={() => undefined} onChange={() => undefined} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onNavigateSource={navigate} onCaretChange={() => undefined} onNotice={() => undefined} />);
    const issues = screen.getByRole('region', { name: /issues/ });
    expect(issues).toHaveTextContent('already declared at line 1');
    fireEvent.click(within(issues).getByRole('button'));
    expect(navigate).toHaveBeenCalledWith('main', 3, 2, 1);
  });

  it('says nothing about a symbol declared in an included file', () => {
    workspace({ id: 'main', name: 'main.asm', language: '6502', modified: false, content: 'INCLUDE "lib.asm"\n.start\n  JSR draw\n  RTS' } as ProjectFile);
    expect(screen.queryByRole('region', { name: /issues/ })).not.toBeInTheDocument();
  });

  it('outlines a project manifest by its fields and points at broken JSON', () => {
    workspace({ id: 'doc', name: 'hero.asset.json', language: 'text', modified: false, content: '{\n  "schema": "8bit-net.pixel-asset",\n  "version": 1\n}' } as ProjectFile);
    expect(within(screen.getByRole('complementary', { name: 'Source outline' })).getByRole('button', { name: /schema/ })).toHaveTextContent('8bit-net.pixel-asset');
    expect(screen.queryByRole('region', { name: /issues/ })).not.toBeInTheDocument();

    cleanup();
    workspace({ id: 'doc', name: 'hero.asset.json', language: 'text', modified: false, content: '{\n  "schema": "8bit-net.pixel-asset",\n' } as ProjectFile);
    expect(screen.getByRole('region', { name: /issues/ })).toHaveTextContent('not valid JSON');
  });

  it('keeps the older flat outline for a language with no adapter', () => {
    workspace({ id: 'bas', name: 'menu.bas', language: 'bbc-basic', modified: false, content: '10 PRINT\n20 DEF PROCdraw\n30 ENDPROC' } as ProjectFile);
    const panel = within(screen.getByRole('complementary', { name: 'Source outline' }));
    expect(panel.getByRole('button', { name: /Line 10/ })).toBeInTheDocument();
    expect(panel.getByRole('button', { name: /PROCdraw/ })).toBeInTheDocument();
    expect(screen.queryByRole('region', { name: /issues/ })).not.toBeInTheDocument();
  });
});

describe('accepting a completion with punctuation, and finding one by scattered characters', () => {
  const assembly = (content: string) => {
    const files: ProjectFile[] = [{ id: 'main', name: 'main.asm', content, language: '6502', modified: false } as ProjectFile];
    return render(<SourceWorkspace files={files} projectFiles={files} activeFileId="main" onSelectFile={() => undefined} onChange={(_id, next) => { files[0]!.content = next; }} onNewFile={() => undefined} onRenameFile={() => undefined} onDeleteFile={() => undefined} onDownloadFile={() => undefined} onSave={() => undefined} onCaretChange={() => undefined} onNotice={() => undefined} />);
  };

  it('accepts an assembly symbol on a comma, and types the comma too', async () => {
    /* `LDA tab,X` is how an indexed operand is written. Committing on the
     * comma is the difference between typing three characters and eleven. */
    const { container } = assembly('.tile_table\n  EQUB 0\n.start\n  LDA tile_ta');
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    await screen.findByRole('option', { name: /tile_table/ });
    fireEvent.keyDown(editor, { key: ',' });
    await waitFor(() => expect((screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement).value).toContain('LDA tile_table,'));
    expect(container.querySelector('.live-completion')).toBeNull();
  });

  it('types the character normally when no completion is open', () => {
    assembly('  LDA tile');
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    /* The same key press must not be swallowed when there is nothing to
     * accept, which is the failure mode that makes commit characters hated. */
    expect(fireEvent.keyDown(editor, { key: ',' })).toBe(true);
  });

  it('finds a symbol by characters that are in it but not at the front, and says so', async () => {
    assembly('.draw_sprite\n  RTS\n.start\n  JSR dsp');
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    const option = await screen.findByRole('option', { name: /draw_sprite/ });
    expect(option).toHaveTextContent('MATCHED OUT OF ORDER');
    /* The characters that matched are marked, so the candidate explains why
     * it is in the list rather than looking like an unrelated suggestion. */
    expect(option.querySelectorAll('mark')).toHaveLength(3);
  });

  it('puts a candidate that starts with what was typed above one that merely contains it', async () => {
    assembly('.draw_sprite\n  RTS\n.ds_helper\n  RTS\n.start\n  JSR ds');
    const editor = screen.getByLabelText('Edit main.asm') as HTMLTextAreaElement;
    editor.setSelectionRange(editor.value.length, editor.value.length);
    fireEvent.keyDown(editor, { code: 'Space', key: ' ', ctrlKey: true });
    await screen.findByRole('option', { name: /ds_helper/ });
    const options = screen.getAllByRole('option').map((option) => option.textContent ?? '');
    expect(options.findIndex((text) => text.includes('ds_helper'))).toBeLessThan(options.findIndex((text) => text.includes('draw_sprite')));
  });
});
