#!/usr/bin/env node
/*
 * The whole claim, in one measurement: a game built here, put on the medium the
 * machine shipped with, and loaded and run by that machine from the tape.
 *
 * Every other script beside this one measures a part. The starters prove a
 * program written here runs; the tape measurements prove a machine loads an
 * image written here; the sprite and song editors prove they generate source
 * that assembles. None of those is the claim the product actually makes, which
 * is that somebody can go from nothing to a game the machine plays — and a
 * chain of working parts is not the same as a working chain.
 *
 * So this builds one: a program, with artwork and music generated by the
 * editors and assembled into it, written to a cassette by the tape authoring,
 * mounted on a real machine, loaded with the machine's own *RUN, and then the
 * machine is asked what it printed.
 *
 * If the machine prints the game's own words, every link held.
 *
 * ROMs are never committed. Run this against firmware you already have:
 *
 *   node scripts/measureGameEndToEnd.mjs <directory containing roms/>
 */
import { argv, exit } from 'node:process';
import { resolve } from 'node:path';
import { TestMachine } from 'jsbeeb/tests/test-machine.js';
import { setNodeBasePath } from 'jsbeeb/src/utils.js';
import { loadTapeFromData } from 'jsbeeb/src/tapes.js';

/**
 * The game.
 *
 * Small on purpose: what is being measured is the journey, not the program. It
 * prints its title, shows that the artwork and the music are really in the
 * binary by reading a byte of each and printing it, and returns.
 */
export const GAME_SOURCE = `
; A whole game, for the purposes of proving the line works end to end.
OSWRCH = &FFEE
OSNEWL = &FFE7
string_pointer = &70

ORG &1900

.start
  LDX #<title
  LDY #>title
  JSR print_string
  JSR OSNEWL
  ; The artwork is in the binary: print the first byte of it as two hex digits.
  LDA sprite_data
  JSR print_hex
  LDA #ASC_SPACE
  JSR OSWRCH
  ; And so is the music.
  LDA song_data
  JSR print_hex
  JSR OSNEWL
  RTS

ASC_SPACE = 32

.print_hex
  PHA
  LSR A
  LSR A
  LSR A
  LSR A
  JSR print_nibble
  PLA
  AND #15
.print_nibble
  CLC
  ADC #48
  CMP #58
  BCC print_nibble_out
  ADC #6
.print_nibble_out
  JMP OSWRCH

.print_string
  STX string_pointer
  STY string_pointer + 1
  LDY #0
.print_string_loop
  LDA (string_pointer),Y
  BEQ print_string_done
  JSR OSWRCH
  INY
  BNE print_string_loop
.print_string_done
  RTS

.title
  EQUS "TAPE GAME LIVES"
  EQUB 0
`;

/** What the machine has to print for the chain to have held. */
export const GAME_TITLE = 'TAPE GAME LIVES';

/** The machines this can be run on, and how each is asked to load a tape. */
export const END_TO_END_MACHINES = Object.freeze([
  Object.freeze({ model: 'B', label: 'BBC Model B', roms: null }),
  Object.freeze({ model: 'Master', label: 'BBC Master', roms: null }),
]);

async function main() {
  const base = argv[2];
  if (!base) {
    console.error('Give the directory holding the roms/ tree this build reads firmware from.');
    exit(2);
  }
  setNodeBasePath(resolve(base));
  const { assemble6502 } = await import('../src/build/assembler6502.ts');
  const { createPixelAssetDocument, generatePixelAssetOutput } = await import('../src/assets/pixelAssetDocument.ts');
  const { createSongDocument, generateSongOutput } = await import('../src/assets/songDocument.ts');
  const { createTapeImage } = await import('../src/media/acornTape.ts');

  /* Artwork and music, from the editors that make them, as source. */
  const artwork = createPixelAssetDocument('sprite');
  artwork.pixels = artwork.pixels.map((_, index) => (index % 3) + 1);
  const artworkSource = generatePixelAssetOutput(artwork).assembly;
  const song = createSongDocument('theme', 8, 'bbc-sn76489');
  song.rows[0][1] = { pitch: 101, volume: 15 };
  const songSource = generateSongOutput(song).assembly;

  const source = `${GAME_SOURCE}\n.sprite_data\n${artworkSource}\n.song_data\n${songSource}\n`;
  const artifact = assemble6502(source, '6502', 0x1900, {}, 'bbc-b');
  const problems = artifact.diagnostics.filter((item) => item.severity !== 'info');
  if (problems.length) {
    console.error('the game did not build:', problems.slice(0, 5).map((item) => `${item.line}: ${item.message}`));
    exit(1);
  }
  console.log(`built ${artifact.bytes.length} bytes, artwork and music included`);

  const image = createTapeImage([{ name: 'GAME', loadAddress: 0x1900, executionAddress: 0x1900, bytes: artifact.bytes }]);
  console.log(`wrote a ${image.length}-byte cassette`);

  let failures = 0;
  for (const machine of END_TO_END_MACHINES) {
    const test = new TestMachine(machine.model);
    await test.initialise();
    test.startCapture();
    await test.runUntilInput(30);
    test.drainText({ raw: true });
    test.processor.acia.setTape(await loadTapeFromData('game.uef', image, test.model));
    await test.type('*TAPE');
    await test.runFor(1_000_000);
    test.drainText({ raw: true });
    /* The machine's own loader and the machine's own launch: nothing here
     * places a byte in its memory. */
    await test.type('*RUN GAME');
    let printed = '';
    for (let i = 0; i < 60 && !printed.includes(GAME_TITLE); i += 1) {
      await test.runFor(2_000_000);
      printed += test.drainText({ raw: true });
    }
    const ran = printed.includes(GAME_TITLE);
    console.log(`${machine.label}: ${ran ? 'played it' : 'did not'} · ${JSON.stringify(printed.trim().slice(-80))}`);
    if (!ran) failures += 1;
  }
  if (failures) exit(1);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) await main();
