/*
 * The keyword tables of each 6502-family BBC BASIC, and what is not here.
 *
 * These are read out of language ROMs by `scripts/extractBasicTokens.mjs`
 * rather than transcribed. A hand-copied table of a hundred and twenty entries
 * has a typo in it, and nothing would find that typo until somebody's program
 * decoded wrongly in one place.
 *
 * What makes the reading trustworthy is that the same reader reproduces the
 * BASIC II table this repository already carried, transcribed independently and
 * by hand, and a contract checks that it still does. All four tables also end
 * at the same keyword, `HIMEM`, which is corroboration that the rule for where
 * a table stops belongs to the table and not to the reader.
 *
 * BASIC V and VI are still absent, and the reason is no longer the one recorded
 * here before. Their table is not a different shape: BBC BASIC V 1.05 lays its
 * out exactly like these, keyword then token then flag, and the same reader
 * takes all 161 entries of it once its terminator stops treating a flag of &80
 * as code. What stops them being shipped is that an ARM BASIC has two-byte
 * tokens, so twenty-three token bytes there are shared by two or three
 * keywords, and which prefix distinguishes them is not settled by anything
 * measured yet. Shipping the table anyway would decode most of a program and
 * corrupt the rest, which is worse than not offering the dialect.
 *
 * Two spellings can share one token: `COLOUR` and `COLOR` are both &FB, and
 * which one a ROM lists first is which one that machine would list back. Both
 * are kept — the token map holds the spelling the ROM lists first, and the
 * order holds every spelling, because an abbreviation resolves against the
 * order and not against the map.
 *
 * No ROM is in this repository and none is needed to build: these are the
 * tables, and the digests say which firmware each came from.
 */

export type BasicDialectId = 'bbc-basic-1' | 'bbc-basic-2' | 'bbc-basic-3' | 'bbc-basic-4' | 'atom-basic';

export interface BasicDialect {
  id: BasicDialectId;
  label: string;
  /** Token to the keyword the ROM lists first for it. */
  tokens: Record<number, string>;
  /** Every keyword, in the ROM's own order, which is how an abbreviation resolves. */
  order: string[];
  /** Spellings that share a token with an earlier one, and what they share it with. */
  aliases: Array<{ keyword: string; sameAs: string; token: number }>;
  provenance: { source: string; sha256: string; detail: string };
}


const BBC_BASIC_1_TOKENS: Record<number, string> = {
  0x80: "AND",
  0x81: "DIV",
  0x82: "EOR",
  0x83: "MOD",
  0x84: "OR",
  0x85: "ERROR",
  0x86: "LINE",
  0x87: "OFF",
  0x88: "STEP",
  0x89: "SPC",
  0x8a: "TAB(",
  0x8b: "ELSE",
  0x8c: "THEN",
  0x8f: "PTR",
  0x90: "PAGE",
  0x91: "TIME",
  0x92: "LOMEM",
  0x93: "HIMEM",
  0x94: "ABS",
  0x95: "ACS",
  0x96: "ADVAL",
  0x97: "ASC",
  0x98: "ASN",
  0x99: "ATN",
  0x9a: "BGET",
  0x9b: "COS",
  0x9c: "COUNT",
  0x9d: "DEG",
  0x9e: "ERL",
  0x9f: "ERR",
  0xa0: "EVAL",
  0xa1: "EXP",
  0xa2: "EXT",
  0xa3: "FALSE",
  0xa4: "FN",
  0xa5: "GET",
  0xa6: "INKEY",
  0xa7: "INSTR(",
  0xa8: "INT",
  0xa9: "LEN",
  0xaa: "LN",
  0xab: "LOG",
  0xac: "NOT",
  0xad: "OPENIN",
  0xae: "OPENOUT",
  0xaf: "PI",
  0xb0: "POINT(",
  0xb1: "POS",
  0xb2: "RAD",
  0xb3: "RND",
  0xb4: "SGN",
  0xb5: "SIN",
  0xb6: "SQR",
  0xb7: "TAN",
  0xb8: "TO",
  0xb9: "TRUE",
  0xba: "USR",
  0xbb: "VAL",
  0xbc: "VPOS",
  0xbd: "CHR$",
  0xbe: "GET$",
  0xbf: "INKEY$",
  0xc0: "LEFT$(",
  0xc1: "MID$(",
  0xc2: "RIGHT$(",
  0xc3: "STR$",
  0xc4: "STRING$(",
  0xc5: "EOF",
  0xc6: "AUTO",
  0xc7: "DELETE",
  0xc8: "LOAD",
  0xc9: "LIST",
  0xca: "NEW",
  0xcb: "OLD",
  0xcc: "RENUMBER",
  0xcd: "SAVE",
  0xcf: "PTR",
  0xd0: "PAGE",
  0xd1: "TIME",
  0xd2: "LOMEM",
  0xd3: "HIMEM",
  0xd4: "SOUND",
  0xd5: "BPUT",
  0xd6: "CALL",
  0xd7: "CHAIN",
  0xd8: "CLEAR",
  0xd9: "CLOSE",
  0xda: "CLG",
  0xdb: "CLS",
  0xdc: "DATA",
  0xdd: "DEF",
  0xde: "DIM",
  0xdf: "DRAW",
  0xe0: "END",
  0xe1: "ENDPROC",
  0xe2: "ENVELOPE",
  0xe3: "FOR",
  0xe4: "GOSUB",
  0xe5: "GOTO",
  0xe6: "GCOL",
  0xe7: "IF",
  0xe8: "INPUT",
  0xe9: "LET",
  0xea: "LOCAL",
  0xeb: "MODE",
  0xec: "MOVE",
  0xed: "NEXT",
  0xee: "ON",
  0xef: "VDU",
  0xf0: "PLOT",
  0xf1: "PRINT",
  0xf2: "PROC",
  0xf3: "READ",
  0xf4: "REM",
  0xf5: "REPEAT",
  0xf6: "REPORT",
  0xf7: "RESTORE",
  0xf8: "RETURN",
  0xf9: "RUN",
  0xfa: "STOP",
  0xfb: "COLOUR",
  0xfc: "TRACE",
  0xfd: "UNTIL",
  0xfe: "WIDTH",
};

const BBC_BASIC_1_ORDER: string[] = ["AND", "ABS", "ACS", "ADVAL", "ASC", "ASN", "ATN", "AUTO", "BGET", "BPUT", "COLOUR", "CALL", "CHAIN", "CHR$", "CLEAR", "CLOSE", "CLG", "CLS", "COS", "COUNT", "DATA", "DEG", "DEF", "DELETE", "DIV", "DIM", "DRAW", "ENDPROC", "END", "ENVELOPE", "ELSE", "EVAL", "ERL", "ERROR", "EOF", "EOR", "ERR", "EXP", "EXT", "FOR", "FALSE", "FN", "GOTO", "GET$", "GET", "GOSUB", "GCOL", "HIMEM", "INPUT", "IF", "INKEY$", "INKEY", "INT", "INSTR(", "LIST", "LINE", "LOAD", "LOMEM", "LOCAL", "LEFT$(", "LEN", "LET", "LOG", "LN", "MID$(", "MODE", "MOD", "MOVE", "NEXT", "NEW", "NOT", "OLD", "ON", "OFF", "OR", "OPENIN", "OPENOUT", "PRINT", "PAGE", "PTR", "PI", "PLOT", "POINT(", "PROC", "POS", "RETURN", "REPEAT", "REPORT", "READ", "REM", "RUN", "RAD", "RESTORE", "RIGHT$(", "RND", "RENUMBER", "STEP", "SAVE", "SGN", "SIN", "SQR", "SPC", "STR$", "STRING$(", "SOUND", "STOP", "TAN", "THEN", "TO", "TAB(", "TRACE", "TIME", "TRUE", "UNTIL", "USR", "VDU", "VAL", "VPOS", "WIDTH", "PAGE", "PTR", "TIME", "LOMEM", "HIMEM"];

export const BBC_BASIC_1: BasicDialect = {
  id: "bbc-basic-1",
  label: "BBC BASIC I",
  tokens: BBC_BASIC_1_TOKENS,
  order: BBC_BASIC_1_ORDER,
  aliases: [],
  provenance: { source: "basic1.rom", sha256: "6dccf62d34a90fc16f102f9dbb3431bbf084e4edcbc21a5f059bbdf6af35b566", detail: "The original BBC Micro language ROM." },
};


const BBC_BASIC_2_TOKENS: Record<number, string> = {
  0x80: "AND",
  0x81: "DIV",
  0x82: "EOR",
  0x83: "MOD",
  0x84: "OR",
  0x85: "ERROR",
  0x86: "LINE",
  0x87: "OFF",
  0x88: "STEP",
  0x89: "SPC",
  0x8a: "TAB(",
  0x8b: "ELSE",
  0x8c: "THEN",
  0x8e: "OPENIN",
  0x8f: "PTR",
  0x90: "PAGE",
  0x91: "TIME",
  0x92: "LOMEM",
  0x93: "HIMEM",
  0x94: "ABS",
  0x95: "ACS",
  0x96: "ADVAL",
  0x97: "ASC",
  0x98: "ASN",
  0x99: "ATN",
  0x9a: "BGET",
  0x9b: "COS",
  0x9c: "COUNT",
  0x9d: "DEG",
  0x9e: "ERL",
  0x9f: "ERR",
  0xa0: "EVAL",
  0xa1: "EXP",
  0xa2: "EXT",
  0xa3: "FALSE",
  0xa4: "FN",
  0xa5: "GET",
  0xa6: "INKEY",
  0xa7: "INSTR(",
  0xa8: "INT",
  0xa9: "LEN",
  0xaa: "LN",
  0xab: "LOG",
  0xac: "NOT",
  0xad: "OPENUP",
  0xae: "OPENOUT",
  0xaf: "PI",
  0xb0: "POINT(",
  0xb1: "POS",
  0xb2: "RAD",
  0xb3: "RND",
  0xb4: "SGN",
  0xb5: "SIN",
  0xb6: "SQR",
  0xb7: "TAN",
  0xb8: "TO",
  0xb9: "TRUE",
  0xba: "USR",
  0xbb: "VAL",
  0xbc: "VPOS",
  0xbd: "CHR$",
  0xbe: "GET$",
  0xbf: "INKEY$",
  0xc0: "LEFT$(",
  0xc1: "MID$(",
  0xc2: "RIGHT$(",
  0xc3: "STR$",
  0xc4: "STRING$(",
  0xc5: "EOF",
  0xc6: "AUTO",
  0xc7: "DELETE",
  0xc8: "LOAD",
  0xc9: "LIST",
  0xca: "NEW",
  0xcb: "OLD",
  0xcc: "RENUMBER",
  0xcd: "SAVE",
  0xcf: "PTR",
  0xd0: "PAGE",
  0xd1: "TIME",
  0xd2: "LOMEM",
  0xd3: "HIMEM",
  0xd4: "SOUND",
  0xd5: "BPUT",
  0xd6: "CALL",
  0xd7: "CHAIN",
  0xd8: "CLEAR",
  0xd9: "CLOSE",
  0xda: "CLG",
  0xdb: "CLS",
  0xdc: "DATA",
  0xdd: "DEF",
  0xde: "DIM",
  0xdf: "DRAW",
  0xe0: "END",
  0xe1: "ENDPROC",
  0xe2: "ENVELOPE",
  0xe3: "FOR",
  0xe4: "GOSUB",
  0xe5: "GOTO",
  0xe6: "GCOL",
  0xe7: "IF",
  0xe8: "INPUT",
  0xe9: "LET",
  0xea: "LOCAL",
  0xeb: "MODE",
  0xec: "MOVE",
  0xed: "NEXT",
  0xee: "ON",
  0xef: "VDU",
  0xf0: "PLOT",
  0xf1: "PRINT",
  0xf2: "PROC",
  0xf3: "READ",
  0xf4: "REM",
  0xf5: "REPEAT",
  0xf6: "REPORT",
  0xf7: "RESTORE",
  0xf8: "RETURN",
  0xf9: "RUN",
  0xfa: "STOP",
  0xfb: "COLOUR",
  0xfc: "TRACE",
  0xfd: "UNTIL",
  0xfe: "WIDTH",
  0xff: "OSCLI",
};

const BBC_BASIC_2_ORDER: string[] = ["AND", "ABS", "ACS", "ADVAL", "ASC", "ASN", "ATN", "AUTO", "BGET", "BPUT", "COLOUR", "CALL", "CHAIN", "CHR$", "CLEAR", "CLOSE", "CLG", "CLS", "COS", "COUNT", "DATA", "DEG", "DEF", "DELETE", "DIV", "DIM", "DRAW", "ENDPROC", "END", "ENVELOPE", "ELSE", "EVAL", "ERL", "ERROR", "EOF", "EOR", "ERR", "EXP", "EXT", "FOR", "FALSE", "FN", "GOTO", "GET$", "GET", "GOSUB", "GCOL", "HIMEM", "INPUT", "IF", "INKEY$", "INKEY", "INT", "INSTR(", "LIST", "LINE", "LOAD", "LOMEM", "LOCAL", "LEFT$(", "LEN", "LET", "LOG", "LN", "MID$(", "MODE", "MOD", "MOVE", "NEXT", "NEW", "NOT", "OLD", "ON", "OFF", "OR", "OPENIN", "OPENOUT", "OPENUP", "OSCLI", "PRINT", "PAGE", "PTR", "PI", "PLOT", "POINT(", "PROC", "POS", "RETURN", "REPEAT", "REPORT", "READ", "REM", "RUN", "RAD", "RESTORE", "RIGHT$(", "RND", "RENUMBER", "STEP", "SAVE", "SGN", "SIN", "SQR", "SPC", "STR$", "STRING$(", "SOUND", "STOP", "TAN", "THEN", "TO", "TAB(", "TRACE", "TIME", "TRUE", "UNTIL", "USR", "VDU", "VAL", "VPOS", "WIDTH", "PAGE", "PTR", "TIME", "LOMEM", "HIMEM"];

export const BBC_BASIC_2: BasicDialect = {
  id: "bbc-basic-2",
  label: "BBC BASIC II",
  tokens: BBC_BASIC_2_TOKENS,
  order: BBC_BASIC_2_ORDER,
  aliases: [],
  provenance: { source: "basic2.rom", sha256: "45bd55dc0f6f0f8f1fe9e2481de7def206565eec8f600ba3068b849ca4132079", detail: "The BBC Micro language ROM this build already carried a hand transcription of." },
};


const BBC_BASIC_3_TOKENS: Record<number, string> = {
  0x80: "AND",
  0x81: "DIV",
  0x82: "EOR",
  0x83: "MOD",
  0x84: "OR",
  0x85: "ERROR",
  0x86: "LINE",
  0x87: "OFF",
  0x88: "STEP",
  0x89: "SPC",
  0x8a: "TAB(",
  0x8b: "ELSE",
  0x8c: "THEN",
  0x8e: "OPENIN",
  0x8f: "PTR",
  0x90: "PAGE",
  0x91: "TIME",
  0x92: "LOMEM",
  0x93: "HIMEM",
  0x94: "ABS",
  0x95: "ACS",
  0x96: "ADVAL",
  0x97: "ASC",
  0x98: "ASN",
  0x99: "ATN",
  0x9a: "BGET",
  0x9b: "COS",
  0x9c: "COUNT",
  0x9d: "DEG",
  0x9e: "ERL",
  0x9f: "ERR",
  0xa0: "EVAL",
  0xa1: "EXP",
  0xa2: "EXT",
  0xa3: "FALSE",
  0xa4: "FN",
  0xa5: "GET",
  0xa6: "INKEY",
  0xa7: "INSTR(",
  0xa8: "INT",
  0xa9: "LEN",
  0xaa: "LN",
  0xab: "LOG",
  0xac: "NOT",
  0xad: "OPENUP",
  0xae: "OPENOUT",
  0xaf: "PI",
  0xb0: "POINT(",
  0xb1: "POS",
  0xb2: "RAD",
  0xb3: "RND",
  0xb4: "SGN",
  0xb5: "SIN",
  0xb6: "SQR",
  0xb7: "TAN",
  0xb8: "TO",
  0xb9: "TRUE",
  0xba: "USR",
  0xbb: "VAL",
  0xbc: "VPOS",
  0xbd: "CHR$",
  0xbe: "GET$",
  0xbf: "INKEY$",
  0xc0: "LEFT$(",
  0xc1: "MID$(",
  0xc2: "RIGHT$(",
  0xc3: "STR$",
  0xc4: "STRING$(",
  0xc5: "EOF",
  0xc6: "AUTO",
  0xc7: "DELETE",
  0xc8: "LOAD",
  0xc9: "LIST",
  0xca: "NEW",
  0xcb: "OLD",
  0xcc: "RENUMBER",
  0xcd: "SAVE",
  0xcf: "PTR",
  0xd0: "PAGE",
  0xd1: "TIME",
  0xd2: "LOMEM",
  0xd3: "HIMEM",
  0xd4: "SOUND",
  0xd5: "BPUT",
  0xd6: "CALL",
  0xd7: "CHAIN",
  0xd8: "CLEAR",
  0xd9: "CLOSE",
  0xda: "CLG",
  0xdb: "CLS",
  0xdc: "DATA",
  0xdd: "DEF",
  0xde: "DIM",
  0xdf: "DRAW",
  0xe0: "END",
  0xe1: "ENDPROC",
  0xe2: "ENVELOPE",
  0xe3: "FOR",
  0xe4: "GOSUB",
  0xe5: "GOTO",
  0xe6: "GCOL",
  0xe7: "IF",
  0xe8: "INPUT",
  0xe9: "LET",
  0xea: "LOCAL",
  0xeb: "MODE",
  0xec: "MOVE",
  0xed: "NEXT",
  0xee: "ON",
  0xef: "VDU",
  0xf0: "PLOT",
  0xf1: "PRINT",
  0xf2: "PROC",
  0xf3: "READ",
  0xf4: "REM",
  0xf5: "REPEAT",
  0xf6: "REPORT",
  0xf7: "RESTORE",
  0xf8: "RETURN",
  0xf9: "RUN",
  0xfa: "STOP",
  0xfb: "COLOR",
  0xfc: "TRACE",
  0xfd: "UNTIL",
  0xfe: "WIDTH",
  0xff: "OSCLI",
};

const BBC_BASIC_3_ORDER: string[] = ["AND", "ABS", "ACS", "ADVAL", "ASC", "ASN", "ATN", "AUTO", "BGET", "BPUT", "COLOR", "CALL", "CHAIN", "CHR$", "CLEAR", "CLOSE", "CLG", "CLS", "COS", "COUNT", "COLOUR", "DATA", "DEG", "DEF", "DELETE", "DIV", "DIM", "DRAW", "ENDPROC", "END", "ENVELOPE", "ELSE", "EVAL", "ERL", "ERROR", "EOF", "EOR", "ERR", "EXP", "EXT", "FOR", "FALSE", "FN", "GOTO", "GET$", "GET", "GOSUB", "GCOL", "HIMEM", "INPUT", "IF", "INKEY$", "INKEY", "INT", "INSTR(", "LIST", "LINE", "LOAD", "LOMEM", "LOCAL", "LEFT$(", "LEN", "LET", "LOG", "LN", "MID$(", "MODE", "MOD", "MOVE", "NEXT", "NEW", "NOT", "OLD", "ON", "OFF", "OR", "OPENIN", "OPENOUT", "OPENUP", "OSCLI", "PRINT", "PAGE", "PTR", "PI", "PLOT", "POINT(", "PROC", "POS", "RETURN", "REPEAT", "REPORT", "READ", "REM", "RUN", "RAD", "RESTORE", "RIGHT$(", "RND", "RENUMBER", "STEP", "SAVE", "SGN", "SIN", "SQR", "SPC", "STR$", "STRING$(", "SOUND", "STOP", "TAN", "THEN", "TO", "TAB(", "TRACE", "TIME", "TRUE", "UNTIL", "USR", "VDU", "VAL", "VPOS", "WIDTH", "PAGE", "PTR", "TIME", "LOMEM", "HIMEM"];

export const BBC_BASIC_3: BasicDialect = {
  id: "bbc-basic-3",
  label: "BBC BASIC III",
  tokens: BBC_BASIC_3_TOKENS,
  order: BBC_BASIC_3_ORDER,
  aliases: [{ keyword: "COLOUR", sameAs: "COLOR", token: 0xfb }],
  provenance: { source: "usbasic3.rom", sha256: "bc6a8d00030ec8478c84bcd03980e0424305d78827ce2a3afb1dd39b1a91a923", detail: "The US BBC Micro language ROM." },
};


const BBC_BASIC_4_TOKENS: Record<number, string> = {
  0x80: "AND",
  0x81: "DIV",
  0x82: "EOR",
  0x83: "MOD",
  0x84: "OR",
  0x85: "ERROR",
  0x86: "LINE",
  0x87: "OFF",
  0x88: "STEP",
  0x89: "SPC",
  0x8a: "TAB(",
  0x8b: "ELSE",
  0x8c: "THEN",
  0x8e: "OPENIN",
  0x8f: "PTR",
  0x90: "PAGE",
  0x91: "TIME",
  0x92: "LOMEM",
  0x93: "HIMEM",
  0x94: "ABS",
  0x95: "ACS",
  0x96: "ADVAL",
  0x97: "ASC",
  0x98: "ASN",
  0x99: "ATN",
  0x9a: "BGET",
  0x9b: "COS",
  0x9c: "COUNT",
  0x9d: "DEG",
  0x9e: "ERL",
  0x9f: "ERR",
  0xa0: "EVAL",
  0xa1: "EXP",
  0xa2: "EXT",
  0xa3: "FALSE",
  0xa4: "FN",
  0xa5: "GET",
  0xa6: "INKEY",
  0xa7: "INSTR(",
  0xa8: "INT",
  0xa9: "LEN",
  0xaa: "LN",
  0xab: "LOG",
  0xac: "NOT",
  0xad: "OPENUP",
  0xae: "OPENOUT",
  0xaf: "PI",
  0xb0: "POINT(",
  0xb1: "POS",
  0xb2: "RAD",
  0xb3: "RND",
  0xb4: "SGN",
  0xb5: "SIN",
  0xb6: "SQR",
  0xb7: "TAN",
  0xb8: "TO",
  0xb9: "TRUE",
  0xba: "USR",
  0xbb: "VAL",
  0xbc: "VPOS",
  0xbd: "CHR$",
  0xbe: "GET$",
  0xbf: "INKEY$",
  0xc0: "LEFT$(",
  0xc1: "MID$(",
  0xc2: "RIGHT$(",
  0xc3: "STR$",
  0xc4: "STRING$(",
  0xc5: "EOF",
  0xc6: "AUTO",
  0xc7: "DELETE",
  0xc8: "LOAD",
  0xc9: "LIST",
  0xca: "NEW",
  0xcb: "OLD",
  0xcc: "RENUMBER",
  0xcd: "SAVE",
  0xce: "EDIT",
  0xcf: "PTR",
  0xd0: "PAGE",
  0xd1: "TIME",
  0xd2: "LOMEM",
  0xd3: "HIMEM",
  0xd4: "SOUND",
  0xd5: "BPUT",
  0xd6: "CALL",
  0xd7: "CHAIN",
  0xd8: "CLEAR",
  0xd9: "CLOSE",
  0xda: "CLG",
  0xdb: "CLS",
  0xdc: "DATA",
  0xdd: "DEF",
  0xde: "DIM",
  0xdf: "DRAW",
  0xe0: "END",
  0xe1: "ENDPROC",
  0xe2: "ENVELOPE",
  0xe3: "FOR",
  0xe4: "GOSUB",
  0xe5: "GOTO",
  0xe6: "GCOL",
  0xe7: "IF",
  0xe8: "INPUT",
  0xe9: "LET",
  0xea: "LOCAL",
  0xeb: "MODE",
  0xec: "MOVE",
  0xed: "NEXT",
  0xee: "ON",
  0xef: "VDU",
  0xf0: "PLOT",
  0xf1: "PRINT",
  0xf2: "PROC",
  0xf3: "READ",
  0xf4: "REM",
  0xf5: "REPEAT",
  0xf6: "REPORT",
  0xf7: "RESTORE",
  0xf8: "RETURN",
  0xf9: "RUN",
  0xfa: "STOP",
  0xfb: "COLOUR",
  0xfc: "TRACE",
  0xfd: "UNTIL",
  0xfe: "WIDTH",
  0xff: "OSCLI",
};

const BBC_BASIC_4_ORDER: string[] = ["AND", "ABS", "ACS", "ADVAL", "ASC", "ASN", "ATN", "AUTO", "BGET", "BPUT", "COLOUR", "CALL", "CHAIN", "CHR$", "CLEAR", "CLOSE", "CLG", "CLS", "COS", "COUNT", "COLOR", "DATA", "DEG", "DEF", "DELETE", "DIV", "DIM", "DRAW", "ENDPROC", "END", "ENVELOPE", "ELSE", "EVAL", "ERL", "ERROR", "EOF", "EOR", "ERR", "EXP", "EXT", "EDIT", "FOR", "FALSE", "FN", "GOTO", "GET$", "GET", "GOSUB", "GCOL", "HIMEM", "INPUT", "IF", "INKEY$", "INKEY", "INT", "INSTR(", "LIST", "LINE", "LOAD", "LOMEM", "LOCAL", "LEFT$(", "LEN", "LET", "LOG", "LN", "MID$(", "MODE", "MOD", "MOVE", "NEXT", "NEW", "NOT", "OLD", "ON", "OFF", "OR", "OPENIN", "OPENOUT", "OPENUP", "OSCLI", "PRINT", "PAGE", "PTR", "PI", "PLOT", "POINT(", "PROC", "POS", "RETURN", "REPEAT", "REPORT", "READ", "REM", "RUN", "RAD", "RESTORE", "RIGHT$(", "RND", "RENUMBER", "STEP", "SAVE", "SGN", "SIN", "SQR", "SPC", "STR$", "STRING$(", "SOUND", "STOP", "TAN", "THEN", "TO", "TAB(", "TRACE", "TIME", "TRUE", "UNTIL", "USR", "VDU", "VAL", "VPOS", "WIDTH", "PAGE", "PTR", "TIME", "LOMEM", "HIMEM"];

export const BBC_BASIC_4: BasicDialect = {
  id: "bbc-basic-4",
  label: "BBC BASIC IV",
  tokens: BBC_BASIC_4_TOKENS,
  order: BBC_BASIC_4_ORDER,
  aliases: [{ keyword: "COLOR", sameAs: "COLOUR", token: 0xfb }],
  provenance: { source: "mos3.20", sha256: "66f86b1161e2c91328755466a286523cdf7c37e155f2a3418c59768cf0733560", detail: "The Master 128 combined MOS image, which carries BASIC IV inside it." },
};


export const BASIC_DIALECTS: BasicDialect[] = [BBC_BASIC_1, BBC_BASIC_2, BBC_BASIC_3, BBC_BASIC_4];

export function basicDialect(id: BasicDialectId): BasicDialect | undefined {
  return BASIC_DIALECTS.find((dialect) => dialect.id === id);
}
