import { apiPath } from '../api/contracts';
import type { BuildDiagnostic } from '../build/assembler6502';
import type { Disassembly, DisassemblyRow } from './types';

export interface ArmAssemblySource {
  source: string;
  filenameExtension: 'sarm';
}

export interface ArmAssemblyVerification {
  verified: boolean;
  diagnostics: BuildDiagnostic[];
  verificationMessage: string;
  toolchain?: string;
}

interface NativeArmVerificationResponse {
  schema?: string;
  result?: { invocation?: { adapterId?: string; adapterVersion?: string }; diagnostics?: BuildDiagnostic[] };
  artifact?: { bytesBase64?: string; origin?: number; entryPoint?: number } | null;
  error?: { message?: string };
}

function hex(value: number, width = 8): string {
  return `0x${(value >>> 0).toString(16).toUpperCase().padStart(width, '0')}`;
}

function wordFor(row: DisassemblyRow): number {
  return (row.bytes[0]! | (row.bytes[1]! << 8) | (row.bytes[2]! << 16) | (row.bytes[3]! << 24)) >>> 0;
}

function sourceLabels(disassembly: Disassembly, customLabels: Record<number, string>): Record<number, string> {
  const result: Record<number, string> = {};
  const used = new Set(['_START']);
  for (const row of disassembly.rows) {
    const requested = customLabels[row.address] ?? disassembly.labels[row.address];
    if (!requested || (row.address === disassembly.entryPoint && customLabels[row.address] === undefined)) continue;
    let candidate = requested;
    let suffix = 2;
    while (used.has(candidate.toUpperCase())) candidate = `${requested}_${suffix++}`;
    used.add(candidate.toUpperCase());
    result[row.address] = candidate;
  }
  return result;
}

function safeComment(value: string): string {
  return value.replace(/[\r\n@]/g, ' ').trim();
}

export function createArmAssemblySource(disassembly: Disassembly, customLabels: Record<number, string> = {}): ArmAssemblySource {
  if (disassembly.processor !== 'arm2' && disassembly.processor !== 'arm3') throw new Error('ARM source export requires an ARM2 or ARM3 analysis');
  const labels = sourceLabels(disassembly, customLabels);
  const lines = [
    `@ Generated by 8bit.dev Acorn IDE from a flow-aware ${disassembly.processor.toUpperCase()} analysis.`,
    `@ Link at ${hex(disassembly.origin)}; entry ${hex(disassembly.entryPoint)}.`,
    '@ .inst retains every decoded word exactly; the readable instruction follows as a comment.',
    '.syntax unified',
    '.section .text',
    '.arm',
    '.arch armv2',
    '.global _start',
    '.type _start, %function',
    '',
  ];
  for (const row of disassembly.rows) {
    if (row.address === disassembly.entryPoint) lines.push('_start:');
    if (labels[row.address]) lines.push(`${labels[row.address]}:`);
    if (row.bytes.length === 4) {
      const description = row.kind === 'instruction'
        ? `${row.mnemonic}${row.operand ? ` ${row.operand}` : ''}${row.comment ? ` — ${row.comment}` : ''}`
        : `${row.mnemonic} ${row.operand} — ${row.comment ?? 'Unreached word'}`;
      lines.push(`  .inst ${hex(wordFor(row))} @ ${safeComment(description)}`);
    } else {
      lines.push(`  .byte ${row.bytes.map((byte) => hex(byte, 2)).join(', ')} @ ${safeComment(row.comment ?? 'Trailing bytes')}`);
    }
  }
  lines.push('', '.size _start, . - _start', '');
  return { source: lines.join('\n'), filenameExtension: 'sarm' };
}

function decodeBase64(value: string): Uint8Array {
  const decoded = atob(value);
  return Uint8Array.from(decoded, (character) => character.charCodeAt(0));
}

function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  return left.length === right.length && left.every((byte, index) => byte === right[index]);
}

export async function verifyArmAssemblySource(
  generated: ArmAssemblySource,
  disassembly: Disassembly,
  originalBytes: Uint8Array,
  signal?: AbortSignal,
): Promise<ArmAssemblyVerification> {
  if ((disassembly.processor !== 'arm2' && disassembly.processor !== 'arm3') || disassembly.origin < 0x8000 || (disassembly.origin & 3) !== 0 || (disassembly.entryPoint & 3) !== 0) {
    return { verified: false, diagnostics: [], verificationMessage: 'Native ARM verification requires aligned load/entry addresses at or above &00008000.' };
  }
  const alignedEnd = (disassembly.origin + Math.max(4, originalBytes.length) + 3) & ~3;
  const maximumAddress = Math.min(0x03ffffff, alignedEnd - 1);
  const requestId = crypto.randomUUID();
  const response = await fetch(apiPath('buildArmBinutils'), {
    method: 'POST', signal, cache: 'no-store',
    headers: { 'Content-Type': 'application/json', 'X-8bit-Net-Request': 'native-build', 'X-Correlation-ID': requestId },
    body: JSON.stringify({
      schema: '8bit-net.native-build-request', version: 1, requestId,
      target: {
        id: 'analysis-export', machineId: 'archimedes-a300', profile: 'debug', profileGoal: 'balanced', debugMetadata: 'none',
        processor: 'arm2', outputName: 'analysis-roundtrip.bin', origin: disassembly.origin, maximumAddress,
        entry: { mode: 'symbol', value: '_start' },
      },
      files: [{ id: 'analysis-source', name: 'analysis-roundtrip.sarm', content: generated.source }],
      sourceUnitIds: ['analysis-source'], defines: {},
    }),
  });
  const body = await response.json().catch(() => null) as NativeArmVerificationResponse | null;
  if (!response.ok || !body?.artifact?.bytesBase64) {
    return {
      verified: false,
      diagnostics: body?.result?.diagnostics ?? [],
      verificationMessage: body?.error?.message ?? `Native ARM verification failed with HTTP ${response.status}.`,
    };
  }
  const bytes = decodeBase64(body.artifact.bytesBase64);
  const verified = body.artifact.origin === disassembly.origin
    && body.artifact.entryPoint === disassembly.entryPoint
    && sameBytes(bytes, originalBytes);
  const adapter = body.result?.invocation;
  const toolchain = adapter?.adapterId && adapter.adapterVersion ? `${adapter.adapterId}@${adapter.adapterVersion}` : undefined;
  return {
    verified,
    diagnostics: body.result?.diagnostics ?? [],
    toolchain,
    verificationMessage: verified
      ? `Verified: pinned GNU ARM2 rebuilt ${bytes.length} bytes exactly at ${hex(disassembly.origin)} with entry ${hex(disassembly.entryPoint)}${disassembly.processor === 'arm3' ? '; .inst verification is byte-level and ARM3 semantics remain the analyser’s responsibility' : ''}.`
      : `Verification failed: native GNU ARM output did not reproduce the original ${originalBytes.length}-byte image exactly.`,
  };
}
