import { assemble6502, type BuildDiagnostic } from '../build/assembler6502';
import { MOS_CALLS } from './disassembler6502';
import type { Disassembly, DisassemblyRow, Processor } from './types';

export interface AssemblySourceExport {
  source: string;
  filenameExtension: 'asm';
  verified: boolean;
  diagnostics: BuildDiagnostic[];
  verificationMessage: string;
}

function hex(value: number, width = 4): string {
  return `&${value.toString(16).toUpperCase().padStart(width, '0')}`;
}

function uniqueLabels(disassembly: Disassembly, customLabels: Record<number, string>): Record<number, string> {
  const result: Record<number, string> = {};
  const used = new Set(Object.values(MOS_CALLS).map((name) => name.toUpperCase()));
  for (const row of disassembly.rows) {
    const requested = customLabels[row.address] ?? disassembly.labels[row.address];
    if (!requested) continue;
    let candidate = requested;
    let suffix = 2;
    while (used.has(candidate.toUpperCase()) || candidate.toUpperCase() === 'ENTRY') {
      candidate = `${requested}_${suffix++}`;
    }
    used.add(candidate.toUpperCase());
    result[row.address] = candidate;
  }
  return result;
}

function sourceOperand(row: DisassemblyRow, disassembly: Disassembly, labels: Record<number, string>): string {
  if (row.target === undefined) return row.operand;
  const label = labels[row.target] ?? MOS_CALLS[row.target];
  // A symbolic operand is always selected as absolute by the deliberately small
  // browser assembler. Retain a literal for zero-page instructions so their
  // original two-byte encoding cannot silently grow to three bytes.
  if (!label || (row.bytes.length === 2 && !row.mnemonic.startsWith('B'))) return row.operand;
  const existing = disassembly.labels[row.target] ?? hex(row.target, row.target <= 0xff ? 2 : 4);
  return row.operand.replace(existing, label);
}

function dataSource(row: DisassemblyRow): string {
  return `EQUB ${row.bytes.map((byte) => hex(byte, 2)).join(',')}`;
}

function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  return left.length === right.length && left.every((byte, index) => byte === right[index]);
}

export function createVerified6502AssemblySource(
  disassembly: Disassembly,
  originalBytes: Uint8Array,
  customLabels: Record<number, string> = {},
): AssemblySourceExport {
  if (disassembly.processor !== '6502' && disassembly.processor !== '65c02') {
    return {
      source: '', filenameExtension: 'asm', verified: false, diagnostics: [],
      verificationMessage: 'Assembly-source round-trip verification is currently available for 6502 and 65C02 analyses.',
    };
  }

  const processor = disassembly.processor as Processor;
  const labels = uniqueLabels(disassembly, customLabels);
  const lines = [
    `; Generated by 8bit.dev Acorn IDE from a flow-aware ${processor.toUpperCase()} analysis.`,
    `; Original image: ${originalBytes.length} bytes, load ${hex(disassembly.origin)}, entry ${hex(disassembly.entryPoint)}.`,
    '; Unreached regions use EQUB so every binary value is represented without string-escape ambiguity.',
    `ORG ${hex(disassembly.origin)}`,
    '',
  ];

  for (const row of disassembly.rows) {
    if (row.address === disassembly.entryPoint) lines.push('.ENTRY');
    if (labels[row.address]) lines.push(`.${labels[row.address]}`);
    const statement = row.kind === 'instruction'
      ? `${row.mnemonic}${row.operand ? ` ${sourceOperand(row, disassembly, labels)}` : ''}`
      : dataSource(row);
    lines.push(`  ${statement}${row.comment ? ` ; ${row.comment}` : ''}`);
  }
  lines.push('');
  const source = lines.join('\n');
  const artifact = assemble6502(source, processor, disassembly.origin);
  const verified = artifact.diagnostics.every((diagnostic) => diagnostic.severity !== 'error')
    && artifact.origin === disassembly.origin
    && artifact.entryPoint === disassembly.entryPoint
    && sameBytes(artifact.bytes, originalBytes);
  return {
    source,
    filenameExtension: 'asm',
    verified,
    diagnostics: artifact.diagnostics,
    verificationMessage: verified
      ? `Verified: reassembled ${artifact.bytes.length} bytes exactly at ${hex(artifact.origin)} with entry ${hex(artifact.entryPoint)}.`
      : `Verification failed: the generated source did not reproduce the original ${originalBytes.length}-byte image exactly.`,
  };
}
