/* The WCAG 2.2 AA conformance checklist, and how each criterion is verified.
 *
 * A conformance claim is worth exactly as much as the evidence behind it, so
 * this records the evidence rather than the claim. Every Level A and AA success
 * criterion is listed with one of four honest answers:
 *
 *   automated   a rule in the release gate decides it, and the rule is named
 *   manual      only a person can decide it, and what they have to do is stated
 *   partial     a rule decides part of it and the rest is manual, with the
 *               split stated rather than glossed
 *   n/a         the product has no content the criterion applies to, with the
 *               reason — never as a way of avoiding the work
 *
 * The distinction that carries the most weight is between `automated` and
 * `manual`. A scan can find a control with no accessible name; it cannot tell
 * whether the name means anything. Recording the second as though the first
 * covered it is how a product ends up believing it is accessible.
 *
 * `n/a` is used sparingly and always with the reason, because it is the entry
 * that is easiest to abuse. Every one here rests on the product genuinely not
 * having that kind of content — no video, no audio track, no authentication,
 * no timed process — and each would stop being `n/a` the day it did.
 */

export type Verification = 'automated' | 'manual' | 'partial' | 'n/a';

export interface Criterion {
  id: string;
  name: string;
  level: 'A' | 'AA';
  verification: Verification;
  /** The gate rule that decides it, the manual step, or the reason for n/a. */
  evidence: string;
}

/* Level A and AA of WCAG 2.2. AAA criteria are out of scope for this claim and
 * are not listed, except where the product happens to meet one and says so
 * elsewhere rather than counting it here. */
export const CRITERIA: readonly Criterion[] = Object.freeze([
  { id: '1.1.1', name: 'Non-text Content', level: 'A', verification: 'partial', evidence: 'The gate rules image-alt and visual-alternatives decide whether an alternative exists. Whether an alternative conveys what the visual conveyed is manual.' },
  { id: '1.2.1', name: 'Audio-only and Video-only (Prerecorded)', level: 'A', verification: 'n/a', evidence: 'The product ships no prerecorded audio or video. Emulator sound is generated by the machine being emulated and is a live output, not media content.' },
  { id: '1.2.2', name: 'Captions (Prerecorded)', level: 'A', verification: 'n/a', evidence: 'No prerecorded video is shipped with the product or its help, so there is nothing to caption.' },
  { id: '1.2.3', name: 'Audio Description or Media Alternative (Prerecorded)', level: 'A', verification: 'n/a', evidence: 'No prerecorded video is shipped, so there is nothing needing an audio description or a media alternative.' },
  { id: '1.2.4', name: 'Captions (Live)', level: 'AA', verification: 'n/a', evidence: 'No live audio or video is presented anywhere in the product; emulator sound is a machine output rather than media.' },
  { id: '1.2.5', name: 'Audio Description (Prerecorded)', level: 'AA', verification: 'n/a', evidence: 'No prerecorded video is shipped, so there is nothing that could carry an audio description.' },
  { id: '1.3.1', name: 'Info and Relationships', level: 'A', verification: 'partial', evidence: 'The gate rules heading-order and landmark-label decide structure and naming. Whether the structure matches the visual grouping is manual.' },
  { id: '1.3.2', name: 'Meaningful Sequence', level: 'A', verification: 'manual', evidence: 'Reading order is judged by a person moving through each workspace with a screen reader. No rule can decide whether an order makes sense.' },
  { id: '1.3.3', name: 'Sensory Characteristics', level: 'A', verification: 'manual', evidence: 'Reviewed by reading every instruction for a reference to shape, position or colour alone.' },
  { id: '1.3.4', name: 'Orientation', level: 'AA', verification: 'automated', evidence: 'The gate measures the workbench at five sizes down to 320 CSS pixels, including portrait shapes, with no orientation locked.' },
  { id: '1.3.5', name: 'Identify Input Purpose', level: 'AA', verification: 'n/a', evidence: 'The product collects no information about the person using it, so no input has a purpose from the WCAG list to identify.' },
  { id: '1.4.1', name: 'Use of Color', level: 'A', verification: 'partial', evidence: 'The gate rule forced-colours decides whether a control survives the system replacing the palette. Whether meaning is carried by colour alone elsewhere is manual.' },
  { id: '1.4.2', name: 'Audio Control', level: 'A', verification: 'manual', evidence: 'Emulator sound never starts on its own; a machine has to be run. Verified by a person starting the workbench and confirming silence.' },
  { id: '1.4.3', name: 'Contrast (Minimum)', level: 'AA', verification: 'automated', evidence: 'The gate rule contrast measures every element that holds text against its own background, at 4.5:1 or 3:1 for large text.' },
  { id: '1.4.4', name: 'Resize Text', level: 'AA', verification: 'automated', evidence: 'The gate measures the workbench at 200% and 400% zoom with nothing clipped or out of reach.' },
  { id: '1.4.5', name: 'Images of Text', level: 'AA', verification: 'manual', evidence: 'Reviewed by confirming that every image in the interface and the help is a screenshot of the product or a diagram, never text rendered as a picture.' },
  { id: '1.4.10', name: 'Reflow', level: 'AA', verification: 'automated', evidence: 'The gate measures at 320 CSS pixels with no horizontal scrolling, nothing past the viewport that cannot be scrolled to, and no control out of reach.' },
  { id: '1.4.11', name: 'Non-text Contrast', level: 'AA', verification: 'partial', evidence: 'The gate rule forced-colours decides whether a control has a visible boundary. Contrast of the boundary itself against its background is manual.' },
  { id: '1.4.12', name: 'Text Spacing', level: 'AA', verification: 'automated', evidence: 'The gate applies the spacing the criterion names and reports any element whose text then exceeds a box that cannot scroll.' },
  { id: '1.4.13', name: 'Content on Hover or Focus', level: 'AA', verification: 'manual', evidence: 'Reviewed by confirming that every hover or focus panel can be dismissed without moving the pointer, stays while the pointer is over it, and persists until dismissed.' },
  { id: '2.1.1', name: 'Keyboard', level: 'A', verification: 'partial', evidence: 'The gate rules keyboard reachability and pointer-alternatives decide that every group is reachable and that dragging and destructive actions have keyboard routes. Whether each route is usable is manual.' },
  { id: '2.1.2', name: 'No Keyboard Trap', level: 'A', verification: 'automated', evidence: 'The gate rule keyboard reachability confirms focus can always leave wherever it is.' },
  { id: '2.1.4', name: 'Character Key Shortcuts', level: 'A', verification: 'automated', evidence: 'Every workbench chord is declared in one binding table, every binding uses a modifier, and each can be changed or unbound in Settings. The table is contract-checked.' },
  { id: '2.2.1', name: 'Timing Adjustable', level: 'A', verification: 'n/a', evidence: 'Nothing in the product has a time limit. A build, a run and a test each continue until they finish or are stopped.' },
  { id: '2.2.2', name: 'Pause, Stop, Hide', level: 'A', verification: 'automated', evidence: 'The gate rule reduced-motion reports anything animating for longer than a twentieth of a second once the preference is set, and nothing moves for five seconds unprompted.' },
  { id: '2.3.1', name: 'Three Flashes or Below Threshold', level: 'A', verification: 'manual', evidence: 'The interface itself does not flash. An emulated machine can flash because the program being written makes it, which is the program author’s content rather than this product’s; the help says so.' },
  { id: '2.4.1', name: 'Bypass Blocks', level: 'A', verification: 'manual', evidence: 'A skip link to the editor is present and is verified by a person following it from a cold load.' },
  { id: '2.4.2', name: 'Page Titled', level: 'A', verification: 'automated', evidence: 'The gate rule document-title requires a non-empty title.' },
  { id: '2.4.3', name: 'Focus Order', level: 'A', verification: 'manual', evidence: 'Judged by a person tabbing through each workspace. A rule can say every group is reachable; it cannot say the order is sensible.' },
  { id: '2.4.4', name: 'Link Purpose (In Context)', level: 'A', verification: 'partial', evidence: 'The gate rule control-name decides that every link has a name. Whether the name describes where it goes is manual.' },
  { id: '2.4.5', name: 'Multiple Ways', level: 'AA', verification: 'manual', evidence: 'The workbench is a single application rather than a set of pages, and offers the workspace rail, the command palette, project search and the go-to dialog as separate routes. Verified by a person.' },
  { id: '2.4.6', name: 'Headings and Labels', level: 'AA', verification: 'partial', evidence: 'The gate rules heading-order and control-name decide that headings and labels exist. Whether each describes its content is manual.' },
  { id: '2.4.7', name: 'Focus Visible', level: 'AA', verification: 'automated', evidence: 'The gate rule focus-visibility focuses every control and requires its appearance to change.' },
  { id: '2.4.11', name: 'Focus Not Obscured (Minimum)', level: 'AA', verification: 'manual', evidence: 'Verified by a person tabbing with each panel and dialog open, confirming the focused control is never fully hidden behind a sticky element.' },
  { id: '2.5.1', name: 'Pointer Gestures', level: 'A', verification: 'manual', evidence: 'The product uses no multipoint or path-based gesture. Verified by review of every pointer handler.' },
  { id: '2.5.2', name: 'Pointer Cancellation', level: 'A', verification: 'manual', evidence: 'Verified by review that no action completes on pointer-down alone.' },
  { id: '2.5.3', name: 'Label in Name', level: 'AA', verification: 'manual', evidence: 'Verified by comparing each visible label with the accessible name that carries it, so speech input matches what is written.' },
  { id: '2.5.4', name: 'Motion Actuation', level: 'A', verification: 'n/a', evidence: 'Nothing in the product is operated by moving or tilting the device, and no motion sensor is read at all.' },
  { id: '2.5.7', name: 'Dragging Movements', level: 'AA', verification: 'automated', evidence: 'The gate rule pointer-alternatives requires anything draggable to declare its keyboard alternative, and refuses an alternative claimed without being stated.' },
  { id: '2.5.8', name: 'Target Size (Minimum)', level: 'AA', verification: 'automated', evidence: 'The gate rule target-size measures every pointer target at 24 by 24 CSS pixels, with the essential exception declared in the markup where it is claimed.' },
  { id: '3.1.1', name: 'Language of Page', level: 'A', verification: 'automated', evidence: 'The gate rule document-language requires a declared language.' },
  { id: '3.1.2', name: 'Language of Parts', level: 'AA', verification: 'n/a', evidence: 'The interface and help are written in one language throughout. Source code shown in the editor is not natural-language content.' },
  { id: '3.2.1', name: 'On Focus', level: 'A', verification: 'manual', evidence: 'Verified by a person tabbing through each workspace confirming nothing changes context on focus alone.' },
  { id: '3.2.2', name: 'On Input', level: 'A', verification: 'manual', evidence: 'Verified by a person changing each control and confirming nothing changes context without being asked.' },
  { id: '3.2.3', name: 'Consistent Navigation', level: 'AA', verification: 'manual', evidence: 'The workspace rail and command palette are in the same place in every workspace. Verified by review.' },
  { id: '3.2.4', name: 'Consistent Identification', level: 'AA', verification: 'manual', evidence: 'Verified by review that the same action carries the same name and icon everywhere it appears.' },
  { id: '3.2.6', name: 'Consistent Help', level: 'A', verification: 'manual', evidence: 'In-app help is reached the same way from every workspace. Verified by review.' },
  { id: '3.3.1', name: 'Error Identification', level: 'A', verification: 'manual', evidence: 'Every refusal in this product names what was refused and why, which is checked by the contracts on each module rather than by a page rule.' },
  { id: '3.3.2', name: 'Labels or Instructions', level: 'A', verification: 'partial', evidence: 'The gate rule control-name decides that every control has a name. Whether the instruction is sufficient is manual.' },
  { id: '3.3.3', name: 'Error Suggestion', level: 'AA', verification: 'manual', evidence: 'Refusals state the remedy as well as the reason. Checked by the contracts on each module and reviewed as prose.' },
  { id: '3.3.4', name: 'Error Prevention (Legal, Financial, Data)', level: 'AA', verification: 'manual', evidence: 'Deleting a file goes to the project trash and can be undone; a revert asks for confirmation and says what it will discard. Verified by a person.' },
  { id: '3.3.7', name: 'Redundant Entry', level: 'A', verification: 'n/a', evidence: 'No process in the product asks for the same information twice, and nothing is entered across more than one step.' },
  { id: '3.3.8', name: 'Accessible Authentication (Minimum)', level: 'AA', verification: 'n/a', evidence: 'The product has no authentication step of any kind; nothing is signed in to and no cognitive function test is set.' },
  { id: '4.1.2', name: 'Name, Role, Value', level: 'A', verification: 'partial', evidence: 'The gate rules control-name and duplicate-id decide that every control has an unambiguous name. Whether roles and values are announced correctly is manual, on each supported screen reader.' },
  { id: '4.1.3', name: 'Status Messages', level: 'AA', verification: 'manual', evidence: 'Status regions are present throughout. Whether each announces at a useful moment is manual: a rule can see the region, not hear it.' },
]);

export interface ConformanceSummary {
  total: number;
  automated: number;
  partial: number;
  manual: number;
  notApplicable: number;
}

export function conformanceSummary(criteria: readonly Criterion[] = CRITERIA): ConformanceSummary {
  const count = (verification: Verification) => criteria.filter((criterion) => criterion.verification === verification).length;
  return {
    total: criteria.length,
    automated: count('automated'),
    partial: count('partial'),
    manual: count('manual'),
    notApplicable: count('n/a'),
  };
}

export interface ConformanceProblem {
  where: string;
  problem: string;
}

/** Check the checklist against the rules it depends on, run by a contract. */
export function validateConformance(criteria: readonly Criterion[] = CRITERIA): ConformanceProblem[] {
  const problems: ConformanceProblem[] = [];
  const seen = new Set<string>();
  for (const criterion of criteria) {
    const where = criterion.id || '(a criterion with no number)';
    if (!/^\d\.\d\.\d+$/.test(criterion.id)) problems.push({ where, problem: 'has no success criterion number' });
    if (seen.has(criterion.id)) problems.push({ where, problem: 'is listed twice' });
    seen.add(criterion.id);
    if (!criterion.name.trim()) problems.push({ where, problem: 'has no name' });
    /* The entry that is easiest to abuse is the one that has to say most. */
    if (criterion.evidence.trim().length < 40) problems.push({ where, problem: 'does not say how it is verified' });
    /* An entry claiming a criterion does not apply has to name the absence
     * that makes it so. Matching prose is crude, so the bar is a stated
     * absence and a real explanation rather than a single phrasing. */
    if (criterion.verification === 'n/a' && (!/\b(?:no|nothing|never|none|not|without)\b/i.test(criterion.evidence) || criterion.evidence.trim().length < 60)) {
      problems.push({ where, problem: 'is marked not applicable without saying what the product does not have' });
    }
    if (criterion.verification === 'partial' && !/manual/i.test(criterion.evidence)) {
      problems.push({ where, problem: 'is marked partial without saying which half is manual' });
    }
  }
  return problems;
}

function table(headings: readonly string[], rows: ReadonlyArray<readonly string[]>): string {
  return [
    `| ${headings.join(' | ')} |`,
    `| ${headings.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}

const LABEL: Record<Verification, string> = {
  automated: 'Automated',
  partial: 'Partly automated',
  manual: 'Manual',
  'n/a': 'Not applicable',
};

/** The document, as Markdown. Deterministic, so a test can compare it. */
export function renderConformanceChecklist(): string {
  const summary = conformanceSummary();
  return [
    '# WCAG 2.2 AA conformance checklist',
    '',
    'This document is generated from the checklist the product maintains beside',
    'its accessibility rules, and a contract fails the release gate whenever the',
    'two stop matching. Regenerate it with `npm run conformance`.',
    '',
    'A conformance claim is worth exactly as much as the evidence behind it, so',
    'this records the evidence rather than the claim. Every Level A and AA',
    'success criterion is listed with how it is verified.',
    '',
    '## What the answers mean',
    '',
    '- **Automated** — a rule in the release gate decides it, and the rule is named. It runs on every build.',
    '- **Partly automated** — a rule decides part of it and the rest is manual. Both halves are stated rather than glossed.',
    '- **Manual** — only a person can decide it, and what they have to do is stated.',
    '- **Not applicable** — the product has no content the criterion applies to, with the reason. Each would stop being not applicable the day the product gained that kind of content.',
    '',
    `Of ${summary.total} Level A and AA success criteria: ${summary.automated} are decided automatically, ${summary.partial} partly, ${summary.manual} by a person, and ${summary.notApplicable} do not apply.`,
    '',
    'The distinction carrying the most weight is between automated and manual. A',
    'scan can find a control with no accessible name; it cannot tell whether the',
    'name means anything. Recording the second as though the first covered it is',
    'how a product ends up believing it is accessible.',
    '',
    '## Criteria',
    '',
    table(
      ['Criterion', 'Name', 'Level', 'Verified', 'Evidence'],
      CRITERIA.map((criterion) => [criterion.id, criterion.name, criterion.level, LABEL[criterion.verification], criterion.evidence]),
    ),
    '',
    '## What is not claimed',
    '',
    'Level AAA is out of scope for this claim. Where the product happens to meet',
    'a AAA criterion — honouring the reduced-motion preference, for one — it is',
    'not counted here, because meeting one criterion of a level is not conformance',
    'to it.',
    '',
    'Screen-reader behaviour on each supported combination is the largest thing',
    'that remains manual and unrecruited. Until representative testers have run',
    'the manual matrix, this document records what is verified and by what, and',
    'makes no overall conformance claim.',
    '',
  ].join('\n');
}
